<?php		 
$this->title = $this->translate('PURCHASE_ORDERS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="purchaseorderid" width="5%">
				<?php echo $this->translate('PURCHASE_ORDERS_PURCHASE_ORDER_ID'); ?>
			</th>
			<th class="title" width="28%">
				<?php echo $this->translate('PURCHASE_ORDERS_TITLE'); ?>
			</th>
			<th class="contactid" width="5%">
				<?php echo $this->translate('PURCHASE_ORDERS_CONTACT'); ?>
			</th>
			<th class="billingaddress" width="20%">
				<?php echo $this->translate('PURCHASE_ORDERS_BILLING_ADDRESS'); ?>
			</th>
			<th class="notes" width="15%">
				<?php echo $this->translate('PURCHASE_ORDERS_NOTES') ?>
			</th>
			<th class="purchaseorderdate" width="8%">
				<?php echo $this->translate('PURCHASE_ORDERS_PURCHASE_ORDER_DATE'); ?>
			</th>
			<th class="total" width="8%">
				<?php echo $this->translate('PURCHASE_ORDERS_TOTAL'); ?>
			</th>
			<th class="state" width="6%">
				<?php echo $this->translate('PURCHASE_ORDERS_STATE'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->purchaseorders as $purchaseorder) : ?>
		<tr class="state<?php echo $purchaseorder->state; ?><?php echo $purchaseorder->pinned ? ' pinned' : ''; ?>">
			<td><input class="id" type="checkbox" value="<?php echo $purchaseorder->id ?>" name="id"/></td>
			<td class="purchaseorderid">
				<?php if($purchaseorder->purchaseorderid) : ?>
					<a href="<?php echo $this->url(array('module'=>'purchases', 'controller'=>'purchaseorder', 'action'=>'edit', 'id'=>$purchaseorder->id)); ?>">
						<?php echo $this->escape($purchaseorder->purchaseorderid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_TITLE') ?>" class="title">
				<a href="<?php echo $this->url(array('module'=>'purchases', 'controller'=>'purchaseorder', 'action'=>'edit', 'id'=>$purchaseorder->id)); ?>">
					<?php echo $purchaseorder->title ? $this->escape($purchaseorder->title) : $this->escape($purchaseorder->id); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_CONTACT') ?>" class="contactid">
				<?php if($purchaseorder->contactid) : ?>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$purchaseorder->cid)); ?>">
						<?php echo $this->escape($purchaseorder->contactid); ?><br/>
						<?php echo $this->escape($purchaseorder->billingname1); ?>
						<?php if($purchaseorder->billingname2) echo "<br/>".$this->escape($purchaseorder->billingname2); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_BILLING_ADDRESS') ?>" class="billingaddress">
				<?php echo $this->escape($purchaseorder->billingstreet); ?><br/>
				<?php echo $this->escape($purchaseorder->billingpostcode); ?><br/>
				<?php echo $this->escape($purchaseorder->billingcity); ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_NOTES') ?>" class="notes">
				<?php if($purchaseorder->notes) : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $purchaseorder->notes; ?>" data-type="textarea"><?php echo $purchaseorder->notes; ?></pre>
				<?php else : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $purchaseorder->notes; ?>" data-type="textarea" data-empty="true"><?php echo $this->translate('TOOLBAR_NEW') ;?></pre>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_PURCHASE_ORDER_DATE') ?>" class="purchaseorderdate">
				<?php if($purchaseorder->purchaseorderdate) echo $this->escape(date("d.m.Y", strtotime($purchaseorder->purchaseorderdate))); ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_TOTAL') ?>" class="total">
				<?php echo $this->escape($purchaseorder->total); ?>
			</td>
			<td data-label="<?php echo $this->translate('PURCHASE_ORDERS_STATE') ?>" class="state">
				<?php if($purchaseorder->state == '105' || $purchaseorder->state == '106') : ?>
					<?php echo $this->translate($this->escape($this->options['states'][$purchaseorder->state])); ?>
				<?php else : ?>
					<span class="editable" data-name="state" data-value="<?php echo $purchaseorder->state; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['states'][$purchaseorder->state])); ?></span>
				<?php endif; ?>
			</td>
			<td class="pin">
				<?php if($purchaseorder->pinned) : ?>
					<input type = "button" onclick = "pin(<?php echo $purchaseorder->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
				<?php else : ?>
					<input type = "button" onclick = "pin(<?php echo $purchaseorder->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
				<?php endif; ?>
			</td>
			<td class="buttons">
				<?php if($purchaseorder->state == '105' || $purchaseorder->state == '106') : ?>
					<?php echo $this->toolbar->viewInline; ?>
				<?php else : ?>
					<?php echo $this->toolbar->editInline; ?>
				<?php endif; ?>
				<?php echo $this->toolbar->copyInline; ?>
				<?php echo $this->toolbar->pdfInline; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td></td>
			<td class="toolbar">
				<?php echo $this->ToolbarBottom(); ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="total">
				<?php echo $this->purchaseorders->total; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
