<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id" width="5%">
				<?php echo $this->translate('ADMIN_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('ADMIN_NAME'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->uoms as $uom) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $uom->id ?>" name="id"/></td>
				<td class="id">
					<?php echo $this->escape($uom->id); ?>
				</td>
				<td class="name">
					<span class="editable" data-name="title"><?php echo $this->escape($uom->title); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy'); ?>
					<?php echo $this->Button('delete'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
			</td>
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->title; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
				<?php //echo $this->toolbar->cancel; ?>
			</td>
		</tr>
	</tbody>
</table>
