<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id" width="5%">
				<?php echo $this->translate('ADMIN_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('ADMIN_USER_NAME'); ?>
			</th>
			<th class="password" width="20%">
				<?php echo $this->translate('ADMIN_PASSWORD'); ?>
			</th>
			<th class="email" width="20%">
				<?php echo $this->translate('ADMIN_EMAIL'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->users as $user) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $user->id ?>" name="id"/></td>
				<td class="id">
					<?php echo $this->escape($user->id); ?>
				</td>
				<td class="username">
					<span class="editable" data-name="username"><?php echo $this->escape($user->username); ?></span>
				</td>
				<td class="password">
					<span class="editable" data-name="password"><?php echo $this->escape($user->password); ?></span>
				</td>
				<td class="email">
					<span class="editable" data-name="email"><?php echo $this->escape($user->email); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy'); ?>
					<?php echo $this->Button('delete'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
			</td>
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->username; ?>
			</td>
			<td>
				<?php echo $this->form->password; ?>
			</td>
			<td>
				<?php echo $this->form->email; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
				<?php //echo $this->toolbar->cancel; ?>
			</td>
		</tr>
	</tbody>
</table>
