<?php
$this->title = $this->translate('ADMIN_USERS');
$this->headTitle($this->title);
echo $this->Messages();
?>

<div class="row">
	<div class="col-sm-4 col-lg-2">
		<?php echo $this->AdminMenu(); ?>
	</div>
	<div class="col-sm-8 col-lg-10">
		<table id="data">
			<thead>
				<tr>
					<th width="2%">
						<?php if($this->user['admin']) : ?>
							<input type="checkbox" class="checkall" name="checkall"/>
						<?php endif; ?>
					</th>
					<th class="id" width="5%">
						<?php echo $this->translate('ADMIN_ID'); ?>
					</th>
					<th class="name" width="20%">
						<?php echo $this->translate('ADMIN_USER_NAME'); ?>
					</th>
					<th class="password" width="20%">
						<?php echo $this->translate('ADMIN_PASSWORD'); ?>
					</th>
					<th class="email" width="20%">
						<?php echo $this->translate('ADMIN_EMAIL'); ?>
					</th>
					<?php if($this->user['admin']) : ?>
						<th class="category" width="12%">
							<?php echo $this->translate('ADMIN_ACTIVATED'); ?>
						</th>
						<th width="8%"></th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->users as $user) : ?>
					<tr>
						<td>
							<?php if($this->user['admin']) : ?>
								<input class="id" type="checkbox" value="<?php echo $user->id ?>" name="id"/>
							<?php else : ?>
								<input class="id" type="hidden" value="<?php echo $user->id ?>" name="id"/>
							<?php endif; ?>
						</td>
						<td class="id">
							<?php echo $this->escape($user->id); ?>
						</td>
						<td class="username">
							<?php if($this->user['admin']) : ?>
								<span class="editable" data-name="username"><?php echo $this->escape($user->username); ?></span>
							<?php else : ?>
								<span><?php echo $this->escape($user->username); ?></span>
							<?php endif; ?>
						</td>
						<td class="password">
							<?php if($this->user['admin']) : ?>
								<span class="editable" data-name="password">******</span>
							<?php else : ?>
								<span>******</span>
							<?php endif; ?>
						</td>
						<td class="email">
							<span class="editable" data-name="email"><?php echo $this->escape($user->email); ?></span>
						</td>
						<?php if($this->user['admin']) : ?>
							<td class="activated">
								<?php echo $this->forms[$user->id]->activated; ?>
							</td>
							<td class="buttons">
								<?php echo $this->Button('copy'); ?>
								<?php echo $this->Button('delete'); ?>
							</td>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
				<?php if($this->user['admin']) : ?>
					<tr class="add">
						<td>
						</td>
						<td>
							<?php echo $this->translate('TOOLBAR_NEW'); ?>
						</td>
						<td>
							<?php echo $this->form->username; ?>
						</td>
						<td>
							<?php echo $this->form->password; ?>
						</td>
						<td>
							<?php echo $this->form->email; ?>
						</td>
						<td>
							<?php echo $this->form->activated; ?>
						</td>
						<td class="buttons">
							<?php echo $this->toolbar->save; ?>
							<?php //echo $this->toolbar->cancel; ?>
						</td>
					</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
