<?php
$this->title = $this->translate('ADMIN_SHOPS');
$this->headTitle($this->title);
echo $this->Messages();
?>

<div class="row">
	<div class="col-sm-4 col-lg-2">
		<?php echo $this->AdminMenu(); ?>
	</div>
	<div class="col-sm-8 col-lg-10">
		<table id="data">
			<thead>
				<tr>
					<th width="2%">
						<?php if($this->user['admin']) : ?>
							<input type="checkbox" class="checkall" name="checkall"/>
						<?php endif; ?>
					</th>
					<th class="id" width="5%">
						<?php echo $this->translate('ADMIN_SHOP_ID'); ?>
					</th>
					<th class="street" width="12%">
						<?php echo $this->translate('ADMIN_TITLE'); ?>
					</th>
					<th class="url" width="20%">
						<?php echo $this->translate('ADMIN_URL'); ?>
					</th>
					<th class="phone" width="12%">
						<?php echo $this->translate('ADMIN_LOGO'); ?>
					</th>
					<th class="postcode" width="7%">
						<?php echo $this->translate('ADMIN_FOOTER'); ?>
					</th>
					<th class="postcode" width="7%">
						<?php echo $this->translate('ADMIN_EMAIL'); ?>
					</th>
					<th class="city" width="10%">
						<?php echo $this->translate('ADMIN_TIMEZONE'); ?>
					</th>
					<th class="country" width="10%">
						<?php echo $this->translate('ADMIN_LANGUAGE'); ?>
					</th>
					<?php if($this->user['admin']) : ?>
						<th class="category" width="12%">
							<?php echo $this->translate('ADMIN_ACTIVATED'); ?>
						</th>
						<th width="8%"></th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->shops as $shop) : ?>
					<tr>
						<td>
							<?php if($this->user['admin']) : ?>
								<input class="id" type="checkbox" value="<?php echo $shop->id ?>" name="id"/>
							<?php else : ?>
								<input class="id" type="hidden" value="<?php echo $shop->id ?>" name="id"/>
							<?php endif; ?>
						</td>
						<td class="id">
							<?php echo $this->escape($shop->id); ?>
						</td>
						<td class="name">
							<span class="editable" data-name="title"><?php echo $this->escape($shop->title); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="url"><?php echo $this->escape($shop->url); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="logo"><?php echo $this->escape($shop->logo); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="footer"><?php echo $this->escape($shop->footer); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="emailsender"><?php echo $this->escape($shop->emailsender); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="timezone"><?php echo $this->escape($shop->timezone); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="language"><?php echo $this->escape($shop->language); ?></span>
						</td>
						<?php if($this->user['admin']) : ?>
							<td class="activated">
								<?php echo $this->forms[$shop->id]->activated; ?>
							</td>
							<td class="buttons">
								<?php echo $this->Button('copy'); ?>
								<?php echo $this->Button('delete'); ?>
							</td>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
				<?php if($this->user['admin']) : ?>
					<tr class="add">
						<td>
						</td>
						<td>
							<?php echo $this->translate('TOOLBAR_NEW'); ?>
						</td>
						<td>
							<?php echo $this->form->title; ?>
						</td>
						<td>
							<?php echo $this->form->url; ?>
						</td>
						<td>
							<?php echo $this->form->logo; ?>
						</td>
						<td>
							<?php echo $this->form->footer; ?>
						</td>
						<td>
							<?php echo $this->form->emailsender; ?>
						</td>
						<td>
						</td>
						<td>
						</td>
						<td>
						</td>
						<td class="buttons">
							<?php echo $this->toolbar->save; ?>
							<?php //echo $this->toolbar->cancel; ?>
						</td>
					</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
