<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('QUOTES_NEW_QUOTE');
$this->headTitle($this->title);
echo $this->CKEditor();
echo $this->ElFinder();
?>

<ul class="tabs">
	<li<?php if($this->activeTab == "#tabOverview") : ?> class="active"<?php endif; ?>>
		<a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW'); ?></a></li>
	<li<?php if($this->activeTab == "#tabPositions") : ?> class="active"<?php endif; ?>>
		<a href="#tabPositions" onclick="getPositions()"><?php echo $this->translate('TABS_POSITIONS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabCustomer") : ?> class="active"<?php endif; ?>>
		<a href="#tabCustomer"><?php echo $this->translate('TABS_CUSTOMER'); ?></a></li>
	<li<?php if($this->activeTab == "#tabShippingAddress") : ?> class="active"<?php endif; ?>>
		<a href="#tabShippingAddress"><?php echo $this->translate('TABS_SHIPPING_ADDRESS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabFiles") : ?> class="active"<?php endif; ?>>
		<a href="#tabFiles"><?php echo $this->translate('TABS_FILES'); ?></a></li>
	<li><a href="#tabFinish" onclick="previewPdf()"><?php echo $this->translate('TABS_FINISH'); ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content<?php if($this->activeTab == '#tabOverview' || !$this->activeTab) : ?> active<?php endif; ?>">
		<form id="quote" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div id="left">
				<dl class="form">
					<?php echo $this->form->id; ?>
					<?php echo $this->form->title; ?>
					<dt id="contactid-label"><label><?php echo $this->translate('QUOTES_CONTACT'); ?></label></dt>
					<dd>
						<?php echo $this->toolbar->select; ?>
						<input id="contactid" type="text" value="<?php echo $this->form->getValue('contactid'); ?>" size="3" readonly="readonly" name="contactid"/>
						<input id="billingname1" type="text" value="<?php echo $this->form->getValue('billingname1'); ?>" size="20" readonly="readonly" name="billingname1"/>
					</dd>
					<?php echo $this->form->deliverydate; ?>
					<?php echo $this->form->paymentmethod; ?>
					<?php echo $this->form->shippingmethod; ?>
					<?php echo $this->form->info; ?>
					<?php echo $this->form->opportunityid; ?>
				</dl>
			</div>
			<div id="right">
				<dl class="form">
					<?php echo $this->form->header; ?>
					<?php echo $this->form->footer; ?>
				</dl>
				<div style="clear:left"></div><br>
				<h3>Textbausteine</h3>
				<h4>DEEC</h4>
Wir danken f&uuml;r Ihre Anfrage und bieten zu unseren &quot;Allgemeinen Gesch&auml;ftsbedingungen&quot; freibleibend an: (unsere AGB&acute;s finden Sie auf <a href="http://www.deec.de">www.deec.de</a>)<br />
<br />
<strong>Lieferung:</strong> Frei Baustelle Deutschland, ausgenommen deutsche Inseln. Abladen bauseits.<br />
<strong>Lieferzeit:</strong> 5-7 Werktage nach Zahlungseingang und technischer Klärung<br />
<br />
<strong>Herstellergarantie:</strong><br />
2 Jahre Herstellergarantie bei Kühlzellen (ausgenommen elektrische Teile), 2 Jahre bei Kühlaggregaten (nur bei nachgewiesener Wartung) und 1 Jahr bei anderen Lieferteilen (einschl. der elektrischen Teile bei Kühlzellen).<br />
<br />
Irrtümer, Änderungen und Zwischenverkauf vorbehalten!

				<h4>BERGCOLD</h4>
Wir danken f&uuml;r Ihre Anfrage und bieten zu unseren &quot;Allgemeinen Gesch&auml;ftsbedingungen&quot; freibleibend an: (unsere AGB&acute;s finden Sie auf <a href="http://www.bergcold.com">www.bergcold.com</a>)<br />
<br />
<strong>Lieferung:</strong> EXW ab Werk Duisburg inkl. Verpackung gem&auml;&szlig; Incoterms 2010<br />
<br />
<strong>Lieferung:</strong> CIP Bestimmungsort innerhalb Deutschlands gemäß Incoterms 2010, ausgenommen Ost- und Nordseeinseln<br />
<br />
<strong>Lieferzeit:</strong> 4-5 Wochen nach Zahlungseingang und Kl&auml;rung aller technischen Fragen und Einzelheiten<br />
<br />
<strong>Lieferzeit:</strong> 3-4 Werktage nach Zahlungseingang und Kl&auml;rung aller technischen Fragen und Einzelheiten<br />
<br />
<strong>Zahlungsbedingungen:</strong> 50% Vorkasse, Rest bei Fertigstellung jedoch vor Verladung der Ware ohne Abzug<br />
<br />
<strong>Zahlungsbedingungen:</strong> Vorkasse ohne Abzug<br />
<br />
<strong>Gew&auml;hrleistung</strong><br />
<strong>Aufstellung im Inland:</strong> Vollkostengew&auml;hrleistung f&uuml;r die Dauer von 12 Monaten ab Inbetriebnahme, jedoch maximal 18 Monate ab Werksauslieferung. In Verbindung mit einem Wartungsvertrag verl&auml;ngert sich die Gew&auml;hrleistung auf 24 Monate.<br />
<strong>Aufstellung im Ausland:</strong> Gew&auml;hrleistung auf Ersatzteile f&uuml;r die Dauer von 12 Monaten ab Inbetriebnahme, jedoch maximal 18 Monate ab Werksauslieferung<br />
<br />
<strong>Nicht im Angebot enthalten sind:</strong> Inbetriebnahme, Aufstellung, Elektroinstallation oder Wasserverrohrung vor Ort.<br />
<br />
<strong>Bei Au&szlig;enaufstellung und Au&szlig;entemperaturen unter +4&deg;C, nur mit Frostschutzzusatz oder eine Verdampfer-Frostschutzheizung einsetzen.</strong>
<br />
<br />Irrtümer, Änderungen und Zwischenverkauf vorbehalten

				<?php /*foreach($this->textblocks as $textblock) : ?>
					<p><?php echo $textblock->text; ?></p>
				<?php endforeach;*/ ?>
			</div>
		</form>
		<div style="clear:left"></div>
	</div>
	<div id="tabCustomer" class="tab_content<?php if($this->activeTab == '#tabCustomer') : ?> active<?php endif; ?>">
		<?php echo $this->toolbar->select; ?>
		<form id="quote" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div id="left">
				<dl class="form">
					<?php echo $this->form->contactid; ?>
					<?php echo $this->form->billingname1; ?>
					<?php echo $this->form->billingname2; ?>
					<?php echo $this->form->billingdepartment; ?>
					<dt><label><b><?php echo $this->translate('CONTACTS_ADDRESS'); ?></b></label></dt>
					<dd></dd>
					<?php echo $this->form->billingstreet; ?>
					<?php echo $this->form->billingpostcode; ?>
					<?php echo $this->form->billingcity; ?>
					<?php echo $this->form->billingcountry; ?>
					<?php echo $this->form->vatin; ?>
					<?php echo $this->form->taxfree; ?>
					<?php if(isset($this->contact)) : ?>
						<?php echo $this->ContactData(); ?>
					<?php endif; ?>
				</dl>
			</div>
			<div id="right">
				<dl class="form">
					<?php echo $this->form->contactinfo; ?>
				</dl>
			</div>
		</form>
		<div style="clear:left"></div>
	</div>
	<div id="tabPositions" class="tab_content<?php if($this->activeTab == '#tabPositions') : ?> active<?php endif; ?>">
		<?php echo $this->ToolbarPositions(); ?>
		<div id="positions"></div>
		<?php echo $this->ToolbarPositions("bottom"); ?>
	</div>
	<div id="tabShippingAddress" class="tab_content<?php if($this->activeTab == '#tabShippingAddress') : ?> active<?php endif; ?>">
		<form id="quote" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div id="left">
				<dl class="form">
					<?php echo $this->form->shippingname1; ?>
					<?php echo $this->form->shippingname2; ?>
					<?php echo $this->form->shippingdepartment; ?>
					<?php echo $this->form->shippingstreet; ?>
					<?php echo $this->form->shippingpostcode; ?>
					<?php echo $this->form->shippingcity; ?>
					<?php echo $this->form->shippingcountry; ?>
					<?php echo $this->form->shippingphone; ?>
				</dl>
			</div>
			<div id="right">
			</div>
		</form>
		<div style="clear:left"></div>
	</div>
	<div id="tabFiles" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
		<div id="elfinder"></div>
		<div style="clear:left"></div>
	</div>
	<div id="tabFinish" class="tab_content">
		<div id="datacheck"></div>
		<form id="quote" enctype="application/x-www-form-urlencoded" action="" method="post">
			<dl class="form">
				<?php echo $this->form->templateid; ?>
				<?php echo $this->form->language; ?>
			</dl>
		</form>
		<div style="clear:left"></div>
		<br/>
		<a href="#" onclick="savePdf()"><?php echo $this->translate('QUOTES_SAVE_AND_BOOK'); ?></a> |
		<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'quote', 'action'=>'download', 'id'=>$this->form->getValue('id')));?>" target="_blank"><?php echo $this->translate('QUOTES_DOWNLOAD_PDF'); ?></a>
		<div style="clear:left"></div>
		<br/>
		<div id="output"></div>
	</div>
</div>

<div id="popup">
	<div id="addCustomer" class="popup_block">
		<?php if($this->form->getValue('contactid')) : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'contactid'=>$this->form->getValue('contactid'), 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php else : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php endif; ?>
	</div>

	<div id="selectPosition" class="popup_block">
		<iframe src="<?php echo $this->url(array('module'=>'items', 'controller'=>'item', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller.'|'.$this->form->getValue('id')));?>" width="100%" height="100%"></iframe>
	</div>
</div>
