<?php
if (isset($this->template['filename']) && file_exists(BASE_PATH . '/templates/modules/sales/quote/' . $this->template['filename'] . '.phtml')) {
	include BASE_PATH . '/templates/modules/sales/quote/' . $this->template['filename'] . '.phtml';
	return;
}

// Set default title and metadata
$this->title = $this->quote['quoteid'] ? $this->translate('QUOTE') . ' ' . $this->quote['quoteid'] : $this->translate('DOCUMENTS_SAMPLE');
$this->headTitle($this->title);

//Config
$client = $this->client;

//Quote
$id = $this->quote['id'];
$quoteid = $this->quote['quoteid'];
$contactid = $this->quote['contactid'];
$vatin = $this->quote['vatin'];
$header = $this->quote['header'];
$footer = $this->quote['footer'];
$created = $this->quote['created'];
$filename = $this->quote['filename'];

// Format dates
$quotedate = formatDate($this->quote['quotedate']);
$deliverydate = formatDate($this->quote['deliverydate']);

//BillingAddress
$billingName1 = $this->quote['billingname1'];
$billingName2 = $this->quote['billingname2'];
$billingDepartment = $this->quote['billingdepartment'];
$billingStreet = $this->quote['billingstreet'];
$billingPostcode = $this->quote['billingpostcode'];
$billingCity = $this->quote['billingcity'];
$billingCountry = $this->translate($this->quote['billingcountry']);

//ShippingAddress
$shippingName1 = $this->quote['shippingname1'];
$shippingName2 = $this->quote['shippingname2'];
$shippingDepartment = $this->quote['shippingdepartment'];
$shippingStreet = $this->quote['shippingstreet'];
$shippingPostcode = $this->quote['shippingpostcode'];
$shippingCity = $this->quote['shippingcity'];
$shippingCountry = $this->quote['shippingcountry'];
if($shippingCountry) $shippingCountry = $this->translate($shippingCountry);
$shippingPhone = $this->quote['shippingphone'];
$shippingAddress = false;
if($shippingName1 || $shippingStreet) $shippingAddress = true;

//Settings
$settings = array();
$settings['displayPrices'] = 1;
$settings['displayDiscounts'] = 0;
$settings['displayOptions'] = 1;

//Positions
$positions = $this->positions;

//Options
$options = $this->options;
$optionSets = $this->optionSets;

//Attributes
$attributesByGroup = $this->attributesByGroup;

// Initialize TCPDF
require_once(BASE_PATH . '/library/Tcpdf/config/tcpdf_config.php');
require_once(BASE_PATH . '/library/Tcpdf/tcpdf.php');
$pdf = initializePdf($this->title, $client);

$pageStart = $pdf->getPage();

//Website
if(isset($this->template) && $this->template['website']) {
	$website = $this->template['website'];
} else {
	$website = $client['website'];
}

///////////////////////////////////////////////////
$entryPages = 0;

if($positions->count() > 0) {
	$positionsArray = $positions->toArray();
	$firstPosition = reset($positionsArray);

	if(isset($this->items[$firstPosition['itemid']]) && isset($this->items[$firstPosition['itemid']]['shopdescription'])) {
		$item = $this->items[$firstPosition['itemid']];
		if(isset($this->media[$firstPosition['itemid']][0]['url'])) $mediaUrl = $this->media[$firstPosition['itemid']][0]['url'];

		//IMPORTANT INFORMATIONS
		$pdf->SetY(40);
		$pdf->setCellPaddings(0, 0, 0, 0);
		$pdf->SetFont('freesans', '', 9);
		$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_QUOTE_ID'), 0, 'L', false, 0, 130);
		if($quoteid) $pdf->MultiCell(40, 5, $quoteid, 0, 'L', false, 1, 160);
		else $pdf->MultiCell(40, 5, ' - - - - - ', 0, 'L', false, 1, 160);
		$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_QUOTE_DATE'), 0, 'L', false, 0, 130);
		if($quotedate) $pdf->MultiCell(28, 5, $quotedate, 0, 'L', false, 1, 160);
		else $pdf->MultiCell(28, 5, ' - - - - - ', 0, 'L', false, 1, 160);
		$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_CUSTOMER_ID'), 0, 'L', false, 0, 130);
		$pdf->MultiCell(28, 5, $contactid, 0, 'L', false, 1, 160);
		if($vatin) {
			$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_VATIN'), 0, 'L', false, 0, 130);
			$pdf->MultiCell(84, 5, $vatin, 0, 'L', false, 1, 160);
		}
		if($deliverydate) {
			$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_DELIVERY_DATE'), 0, 'L', false, 0, 130);
			$pdf->MultiCell(84, 5, $deliverydate, 0, 'L', false, 1, 160);
		}
		$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_SALES_PERSON'), 0, 'L', false, 0, 130);
		$pdf->MultiCell(84, 5, $this->quote['contactperson'], 0, 'L', false, 1, 160);
		$pdf->ln(8);
		$y = $pdf->GetY();

		$pdf->setCellPaddings(0, 0, 0, 0);

		$x = $pdf->GetX()+5;
		$pdf->SetFont('freesansb', 'B', 15);
		$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('QUOTE'), 'UTF-8'), 0, 'L', false, 1, $x, 20);
		$pdf->ln(22);

		//LETTERHEAD
		$pdf->SetFont('freesans', '', 7);
		if(isset($this->template) && isset($this->template['company']) && $this->template['company']) {
			$address = $this->template['company'];
		} else {
			$address = $client['company'];
			if($client['address']) $address .= ', '.$client['address'];
			if($client['postcode']) $address .= ', '.$client['postcode'];
			if($client['city']) $address .= ' '.$client['city'];
		}
		$pdf->MultiCell(70, 4, $address, 'B', 'L', false, 1, $x);
		$pdf->ln(4);
		$pdf->SetFont('freesans', '', 10);

		//Contact adress
		if($contactid) {
			$pdf->MultiCell(70, 0, $billingName1, 0, 'L', false, 1, $x);
			if($billingName2) $pdf->MultiCell(70, 0, $billingName2, 0, 'L', false, 1, $x);
			if($billingDepartment) $pdf->MultiCell(70, 0, $billingDepartment, 0, 'L', false, 1, $x);
			if($billingStreet) $pdf->MultiCell(70, 0, $billingStreet, 0, 'L', false, 1, $x);
			$pdf->MultiCell(70, 0, $billingPostcode.' '.$billingCity, 0, 'L', false, 1, $x);
			$pdf->MultiCell(70, 0, $billingCountry, 0, 'L', false, 1, $x);
			$pdf->ln(20);
			if($y > $pdf->GetY()) $pdf->SetY($y);
		}

		$pdf->SetFont('freesans', 'B', 12);
		if($this->quote['subject']) $pdf->MultiCell(165, 0, $this->translate('QUOTES_SUBJECT') . ': ' . $this->quote['subject'], 0, 'L', false, 1, 20, '', true, 0);
		if($this->quote['reference']) $pdf->MultiCell(165, 0, $this->translate('QUOTES_REFERENCE') . ': ' . $this->quote['reference'], 0, 'L', false, 1, 20, '', true, 0);
		$pdf->SetFont('freesans', '', 10);
		$pdf->MultiCell(165, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(165, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(165, 0, 'Vielen Dank für Ihre Anfrage. Im Anhang finden Sie unser Angebot.', 0, 'L', false, 1, 20, '', true, 0);
		$y = $pdf->GetY();
		if(isset($mediaUrl)) $pdf->Image(BASE_PATH.'/media/1/0/100/images/'.$mediaUrl, 120, '', 85, 0, '', '', 'N');
		$pdf->SetFont('freesans', 'B', 10);
		$pdf->SetY($y+8);
		$pdf->MultiCell(100, 0, 'Inhalt des Angebots', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->SetFont('freesans', '', 10);
		$pdf->MultiCell(45, 0, '1. Produktbeschreibung', 0, 'L', false, 0, 20, '', true, 0);
		$xIndex1 = $pdf->GetX();
		$yIndex1 = $pdf->GetY();
		$pdf->ln();
		$pdf->MultiCell(45, 0, '2. Verkaufsangebot', 0, 'L', false, 0, 20, '', true, 0);
		$xIndex2 = $pdf->GetX();
		$yIndex2 = $pdf->GetY();
		$pdf->ln();
		$pdf->MultiCell(45, 0, '3. Verkaufsbedingungen', 0, 'L', false, 0, 20, '', true, 0);
		$xIndex3 = $pdf->GetX();
		$yIndex3 = $pdf->GetY();
		$pdf->ln();
		$pdf->MultiCell(45, 0, '4. Optionale Ausstattung', 0, 'L', false, 0, 20, '', true, 0);
		$xIndex4 = $pdf->GetX();
		$yIndex4 = $pdf->GetY();
		$pdf->ln();
		$pdf->MultiCell(45, 0, '5. Bilder und Zeichnungen', 0, 'L', false, 0, 20, '', true, 0);
		$xIndex5 = $pdf->GetX();
		$yIndex5 = $pdf->GetY();
		$pdf->ln();
		$pdf->MultiCell(100, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, 'Vielen Dank für Ihr Interesse an unseren Produkten. Wir stehen Ihnen bei Rückfragen gerne zur Verfügung.', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, 'Mit freundlichen Grüßen', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, $this->quote['contactperson'], 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, '', 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, $client['company'], 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, $client['address'], 0, 'L', false, 1, 20, '', true, 0);
		$pdf->MultiCell(100, 0, $client['postcode'] . ' ' . $client['city'], 0, 'L', false, 1, 20, '', true, 0);

		addPage($contactid, $quoteid, $quotedate, $website, $this->template, [$this, 'translate'], $pdf);

		$descriptionStart = $pdf->GetPage();

		$pdf->SetFont('freesansb', 'B', 15);
		$pdf->MultiCell(0, 0, $item['title'], 0, 'L', false, 1, '', '');
		$pdf->ln(4);
		$pdf->SetFont('freesans', '', 9);
		if($item['shopdescription']) $pdf->MultiCell(180, 0, removeImages($item['shopdescription']), 0, 'L', false, 1, '', '', true, 0, true);
		$pdf->ln(4);
		$includedOptions = 0;
		foreach($positions as $position) {
			if(isset($options[$position->id])) {
				foreach($optionSets[$position->id] as $optionSet) {
					foreach($options[$position->id][$optionSet->id] as $option) {
						if($option->price == 0) {
							$includedOptions = 1;
							break;
						}
					}
				}
			}
		}
		if($includedOptions) {
			foreach($positions as $position) {
				if(isset($options[$position->id])) {
					$pdf->SetFont('freesans', 'B', 13);
					$pdf->MultiCell(175, 0, 'Eigenschaften und bereits inkludierte Ausstattung für '.$position->sku.' '.$position->title, 0, 'L', false, 1, '', '', true, 0);
					foreach($optionSets[$position->id] as $optionSet) {
						if($pdf->getY() > 250) addPage($contactid, $quoteid, $quotedate, $website, $this->template, [$this, 'translate'], $pdf);
						$pdf->SetFont('freesans', 'B', 10);
						//$pdf->MultiCell(145, 0, $optionSet->title, 0, 'L', false, 0, '', '', true, 0);
						//$pdf->MultiCell(30, 0, "", 0, 'R', false, 1, '', '', true, 0);
						$pdf->SetFont('freesans', '', 9);
						foreach($options[$position->id][$optionSet->id] as $option) {
							if($option->price == 0) {
								$pdf->MultiCell(15, 0, $option->sku, 0, 'L', false, 0, '', '', true, 0);
								$pdf->SetFont('freesans', 'B', 9);
								$pdf->MultiCell(130, 0, $option->title, 0, 'L', false, 0, '', '', true, 0);
								$pdf->SetFont('freesans', '', 9);
								$pdf->MultiCell(30, 0, 'bereits enthalten', 0, 'R', false, 1, 160, '', true, 0);
								if($option->description) $pdf->MultiCell(120, 0, $option->description, 0, 'L', false, 1, 30, '', true, 0);
							}
						}
					}
					$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-2, true, 0);
					$pdf->setY($pdf->getY()+2);
				}
			}
		}

		$entryPages = $pdf->GetPage();
		$descriptionEnd = $pdf->GetPage();

		$pdf->AddPage();
	}
}
///////////////////////////////////////////////////


$offerStart = $pdf->GetPage();
$offerEnd = $pdf->GetPage();

//IMPORTANT INFORMATIONS
$pdf->SetY(40);
$pdf->setCellPaddings(0, 0, 0, 0);
$pdf->SetFont('freesans', '', 9);
$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_QUOTE_ID'), 0, 'L', false, 0, 130);
if($quoteid) $pdf->MultiCell(40, 5, $quoteid, 0, 'L', false, 1, 160);
else $pdf->MultiCell(40, 5, ' - - - - - ', 0, 'L', false, 1, 160);
$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_QUOTE_DATE'), 0, 'L', false, 0, 130);
if($quotedate) $pdf->MultiCell(28, 5, $quotedate, 0, 'L', false, 1, 160);
else $pdf->MultiCell(28, 5, ' - - - - - ', 0, 'L', false, 1, 160);
$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_CUSTOMER_ID'), 0, 'L', false, 0, 130);
$pdf->MultiCell(28, 5, $contactid, 0, 'L', false, 1, 160);
if($vatin) {
	$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_VATIN'), 0, 'L', false, 0, 130);
	$pdf->MultiCell(84, 5, $vatin, 0, 'L', false, 1, 160);
}
if($deliverydate) {
	$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_DELIVERY_DATE'), 0, 'L', false, 0, 130);
	$pdf->MultiCell(84, 5, $deliverydate, 0, 'L', false, 1, 160);
}
$pdf->MultiCell(30, 5, $this->translate('DOCUMENTS_SALES_PERSON'), 0, 'L', false, 0, 130);
$pdf->MultiCell(84, 5, $this->quote['contactperson'], 0, 'L', false, 1, 160);
$pdf->ln(8);
$y = $pdf->GetY();

//Shipping Address
if($shippingAddress) {
	$pdf->SetFont('freesansb', 'B', 10);
	$pdf->MultiCell(70, 0, $this->translate('DOCUMENTS_SHIPPING_ADDRESS'), 0, 'L', false, 1, 130);
	$pdf->SetFont('freesans', '', 10);
	$pdf->MultiCell(70, 0, $shippingName1, 0, 'L', false, 1, 130);
	if($shippingName2) $pdf->MultiCell(70, 0, $shippingName2, 0, 'L', false, 1, 130);
	if($shippingDepartment) $pdf->MultiCell(70, 0, $shippingDepartment, 0, 'L', false, 1, 130);
	$pdf->MultiCell(70, 0, $shippingStreet, 0, 'L', false, 1, 130);
	$shippingPostcodeCity = '';
	if($shippingPostcode) $shippingPostcodeCity .= $shippingPostcode.' ';
	if($shippingCity) $shippingPostcodeCity .= $shippingCity;
	if($shippingPostcodeCity) $pdf->MultiCell(70, 0, $shippingPostcodeCity, 0, 'L', false, 1, 130);
	if($shippingCountry) $pdf->MultiCell(70, 0, $shippingCountry, 0, 'L', false, 1, 130);
	if($shippingPhone) $pdf->MultiCell(70, 0, $this->translate('DOCUMENTS_PHONE').' '.$shippingPhone, 0, 'L', false, 1, 130);
	$pdf->ln(10);
	$y = $pdf->GetY();
}

$pdf->setCellPaddings(0, 0, 0, 0);

$x = $pdf->GetX()+5;
$pdf->SetFont('freesansb', 'B', 15);
$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('QUOTE'), 'UTF-8'), 0, 'L', false, 1, $x, 20);
$pdf->ln(22);

//LETTERHEAD
$pdf->SetFont('freesans', '', 7);
if(isset($this->template) && isset($this->template['company']) && $this->template['company']) {
	$address = $this->template['company'];
} else {
	$address = $client['company'];
	if($client['address']) $address .= ', '.$client['address'];
	if($client['postcode']) $address .= ', '.$client['postcode'];
	if($client['city']) $address .= ' '.$client['city'];
}
$pdf->MultiCell(70, 4, $address, 'B', 'L', false, 1, $x);
$pdf->ln(4);
$pdf->SetFont('freesans', '', 10);

//Contact adress
if($contactid) {
	$pdf->MultiCell(70, 0, $billingName1, 0, 'L', false, 1, $x);
	if($billingName2) $pdf->MultiCell(70, 0, $billingName2, 0, 'L', false, 1, $x);
	if($billingDepartment) $pdf->MultiCell(70, 0, $billingDepartment, 0, 'L', false, 1, $x);
	if($billingStreet) $pdf->MultiCell(70, 0, $billingStreet, 0, 'L', false, 1, $x);
	$pdf->MultiCell(70, 0, $billingPostcode.' '.$billingCity, 0, 'L', false, 1, $x);
	$pdf->MultiCell(70, 0, $billingCountry, 0, 'L', false, 1, $x);
	$pdf->ln(20);
	if($y > $pdf->GetY()) $pdf->SetY($y);
}

//HEADER
if($header) {
	$pdf->SetFont('freesans', '', 9);
	$pdf->MultiCell(175, 0, $header, 0, 'L', false, 1, $x, '', $reseth=true, $stretch=0, $ishtml=true);
	$pdf->ln(4);
}

if(count($positions)) {
	$pdf->setCellPaddings(1, 0, 0, 0);

	$pdf->SetFont('freesansb', 'B', 8);

	//POSITIONS HEADER
	positionsHeader($settings, $pdf, [$this, 'translate']);

	//POSITIONS
	$offerStartPage = $pdf->GetPage();
	positions($positions, $attributesByGroup, $settings, $pdf);
	$offerEndPage = $pdf->GetPage();

	//TOTAL BOX
	if($settings['displayPrices']) {
		totalBox($pdf, $positions, $settings, $this->quote, [$this, 'translate']);
	}
	$offerEnd = $pdf->GetPage();

	//FOOTER
	$pdf->AddPage();
	$footerStartPage = $pdf->GetPage();
	footer($footer, $pdf);
	$footerEndPage = $pdf->GetPage();

	//OPTIONS
	$optionsStartPage = $pdf->GetPage()+1;
	if($settings['displayOptions'] && isset($options)) {
		options($positions, $options, $optionSets, $settings, $pdf);
	}
	$optionsEndPage = $pdf->GetPage();
}

$imagesStartPage = $pdf->GetPage()+1;
if($positions->count() > 0) {
	$positionsArray = $positions->toArray();
	$firstPosition = reset($positionsArray);
	if(isset($this->media[$firstPosition['itemid']])) {
		foreach($this->media[$firstPosition['itemid']] as $media) {
			$pdf->AddPage();
			$pdf->ln(4);
			$pdf->SetFont('freesansb', 'B', 11);
			$pdf->MultiCell(108, 0, $media['title'], 0, 'L', false, 1, '', '', true, 0);
			$pdf->SetFont('freesansb', '', 9);
			$pdf->MultiCell(108, 0, 'Abbildung ähnlich', 0, 'L', false, 1, '', '', true, 0);
			$pdf->ln(4);
			$pdf->Image(BASE_PATH.'/media/1/0/100/images/'.$media['url'], 20, '', 165, 0, '', '', 'N');
			$pdf->SetFont('freesansb', '', 10);
		}
	}
}
$imagesEndPage = $pdf->GetPage();

$i = 1;
$lastPage = $pdf->getNumPages();
while($i <= $lastPage) {
	$pdf->setPage($i);

	if(!$quoteid) {
		sample($pdf, strtoupper($this->translate('DOCUMENTS_SAMPLE')));
	}

	if($this->quote['state'] == 7) {
		cancelled($pdf, strtoupper($this->translate('DOCUMENTS_CANCELLED')));
	}
	if($i == 1) {
		addLogo(145, 10, 50, $website, $this->template, $pdf);
		$pdf->SetFont('freesans', '', 10);
		if(isset($xIndex1) && isset($yIndex1)) {
			if($descriptionEnd > $descriptionStart) {
				$pdf->MultiCell(30, 0, '(Seite '. $descriptionStart.'-'.$descriptionEnd.')', 0, 'L', false, 0, $xIndex1, $yIndex1-1, true, 0);
			} else {
				$pdf->MultiCell(30, 0, '(Seite '. $descriptionStart.')', 0, 'L', false, 0, $xIndex1, $yIndex1-1, true, 0);
			}
		} if(isset($xIndex2) && isset($yIndex2)) {
			if($offerEnd > $offerStart) {
				$pdf->MultiCell(30, 0, '(Seite '. $offerStart.'-'.$offerEnd.')', 0, 'L', false, 0, $xIndex2, $yIndex2-1, true, 0);
			} else {
				$pdf->MultiCell(30, 0, '(Seite '. $offerStart.')', 0, 'L', false, 0, $xIndex2, $yIndex2-1, true, 0);
			}
		} if(isset($xIndex3) && isset($yIndex3)) {
			if($footerEndPage > $footerStartPage) {
				$pdf->MultiCell(30, 0, '(Seite '. $footerStartPage.'-'.$footerEndPage.')', 0, 'L', false, 0, $xIndex3, $yIndex3-1, true, 0);
			} else {
				$pdf->MultiCell(30, 0, '(Seite '. $footerStartPage.')', 0, 'L', false, 0, $xIndex3, $yIndex3-1, true, 0);
			}
		} if(isset($xIndex4) && isset($yIndex4)) {
			if($optionsEndPage > $optionsStartPage) {
				$pdf->MultiCell(30, 0, '(Seite '. $optionsStartPage.'-'.$optionsEndPage.')', 0, 'L', false, 0, $xIndex4, $yIndex4-1, true, 0);
			} else {
				$pdf->MultiCell(30, 0, '(Seite '. $optionsStartPage.')', 0, 'L', false, 0, $xIndex4, $yIndex4-1, true, 0);
			}
		} if(isset($xIndex5) && isset($yIndex5)) {
			if($imagesEndPage > $imagesStartPage) {
				$pdf->MultiCell(30, 0, '(Seite '. $imagesStartPage.'-'.$imagesEndPage.')', 0, 'L', false, 0, $xIndex5, $yIndex5-1, true, 0);
			} else {
				$pdf->MultiCell(30, 0, '(Seite '. $imagesStartPage.')', 0, 'L', false, 0, $xIndex5, $yIndex5-1, true, 0);
			}
		}
	} elseif($i < (1 + $entryPages)) {
		addLogo(145, 10, 50, $website, $this->template, $pdf);

		$pdf->SetFont('freesansb', 'B', 10);
		$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('1. Produktbeschreibung'), 'UTF-8'), 0, 'L', false, 1, 16, 10);
		$pdf->ln(4);

		//New page info box
		$pdf->setCellPaddings(1, 1, 0, 0);
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_QUOTE_ID').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		if($quoteid) $pdf->Write(0, $quoteid.'   ');
		else $pdf->Write(0, ' - - - - -  ');
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_QUOTE_DATE').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		if($quotedate) $pdf->Write(0, $quotedate.'   ');
		else $pdf->Write(0, ' - - - - -  ');
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_CUSTOMER_ID').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		$pdf->Write(0, $contactid);
		$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY(), true, 0);
		$pdf->ln();
	} elseif($i == (1 + $entryPages)) {
		addLogo(145, 10, 50, $website, $this->template, $pdf);
	} elseif($i > (1 + $entryPages)) {
		addLogo(155, 10, 40, $website, $this->template, $pdf);

		if(($i >= $footerStartPage) && ($i <= $footerEndPage)) {
			$pdf->SetFont('freesansb', 'B', 10);
			$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('3. Verkaufsbedingungen'), 'UTF-8'), 0, 'L', false, 1, 16, 10);
			$pdf->ln(4);
		} elseif(($i >= $optionsStartPage) && ($i <= $optionsEndPage)) {
			$pdf->SetFont('freesansb', 'B', 10);
			$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('4. Optionale Ausstattung'), 'UTF-8'), 0, 'L', false, 1, 16, 10);
			$pdf->ln(4);
		} elseif(($i >= $imagesStartPage) && ($i <= $imagesEndPage)) {
			$pdf->SetFont('freesansb', 'B', 10);
			$pdf->MultiCell(0, 0, mb_strtoupper($this->translate('5. Bilder und Zeichnungen'), 'UTF-8'), 0, 'L', false, 1, 16, 10);
			$pdf->ln(4);
		}

		$y = $pdf->GetY();
		$pdf->SetY(20);

		//New page info box
		$pdf->setCellPaddings(1, 1, 0, 0);
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_QUOTE_ID').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		if($quoteid) $pdf->Write(0, $quoteid.'   ');
		else $pdf->Write(0, ' - - - - -  ');
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_QUOTE_DATE').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		if($quotedate) $pdf->Write(0, $quotedate.'   ');
		else $pdf->Write(0, ' - - - - -  ');
		$pdf->SetFont('freesans', '', 8);
		$pdf->Write(0, $this->translate('DOCUMENTS_CUSTOMER_ID').' ');
		$pdf->SetFont('freesansb', 'B', 8);
		$pdf->Write(0, $contactid);
		$pdf->ln();

		$pdf->setCellPaddings(1, 0, 0, 0);

		$pdf->SetFont('freesansb', 'B', 8);

		//POSITIONS HEADER
		$pdf->Cell(10, 5, $this->translate('DOCUMENTS_POSITION'), 'LTB');
		$pdf->setCellPaddings(0, 0, 0, 0);
		$pdf->Cell(98, 5, $this->translate('DOCUMENTS_DESCRIPTION'), 'TB');
		$pdf->Cell(10, 5, $this->translate('DOCUMENTS_QUANTITY'), 'TB');
		$pdf->Cell(12, 5, $this->translate('DOCUMENTS_UOM'), 'TB', 0, 'C');
		$pdf->Cell(25, 5, $this->translate('DOCUMENTS_PRICE_SINGLE'), 'TB', 0, 'C');
		$pdf->Cell(25, 5, $this->translate('DOCUMENTS_PRICE_TOTAL'), 'TBR', 0, 'C');
		$pdf->ln(5);
	}

	$pdf->setCellPaddings(0, 2, 0, 2);
	$pdf->SetAutoPageBreak(false);
	$pdf->SetFont('freesans', '', 7);

	//Footer
	$x = 12;
	$pdf->SetY(270);
	foreach($this->footers as $footer) {
		$width = $footer->width ? $footer->width : 40;
		$pdf->MultiCell($width, 3, $footer->text, 0, 'L', false, 0, $x);
		$x += $width;
	}

	// Page number
	$pdf->SetY(284);
	$pdf->SetFont('helvetica', 'I', 8);
	$pdf->Cell(0, 10, $this->translate('DOCUMENTS_PAGE').' '.$pdf->getAliasNumPage().'/'.$pdf->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
	$pdf->SetFont('freesans', '', 8);

	$pdf->SetAutoPageBreak(true, 30);

	$pdf->SetY($y);
	++$i;
}

//Close and output PDF document
if($this->action == 'download') {
	if($quoteid) $pdf->Output($filename, 'D');
	else $pdf->Output($this->translate('DOCUMENTS_SAMPLE').'_Angebot_'.$billingName1.'.pdf', 'D');
} elseif($this->contact) {
	$path = BASE_PATH.'/files/contacts/';
	$dir1 = substr($client['id'], 0, 1);
	if(strlen($client['id']) > 1) $dir2 = substr($client['id'], 1, 1);
	else $dir2 = '0';
	$dir3 = substr($this->contact['id'], 0, 1).'/';
	if(strlen($this->contact['id']) > 1) $dir4 = substr($this->contact['id'], 1, 1).'/';
	else $dir4 = '0/';
	$url = $dir1.'/'.$dir2.'/'.$client['id'].'/'.$dir3.'/'.$dir4.'/'.$this->contact['id'].'/';
	if($quoteid) {
		if(!file_exists($path.$url.$filename))
			$pdf->Output($path.$url.$filename, 'F');
		$html = '<iframe src="'.$this->baseUrl().'/files/contacts/'.$url.$filename.'?'.time().'" width="900px" height="500px">';
	} else {
		$pdf->Output(BASE_PATH.'/cache/quote/'.$id.'.pdf', 'F');
		$html = '<p><a href="#" onclick="savePdf()">'.$this->translate('QUOTES_SAVE_AND_BOOK').'</a> |
		<a href="'.$this->url(array('module'=>'sales', 'controller'=>'quote', 'action'=>'download', 'id'=>$id)).'" target="_blank">'.$this->translate('QUOTES_DOWNLOAD_PDF').'</a></p>
		<iframe src="'.$this->baseUrl().'/cache/quote/'.$id.'.pdf?'.time().'" width="900px" height="500px"><br/>';
	}
	echo $html;
} else {
	echo '<p><strong>'.$this->translate('DOCUMENTS_THERE_IS_NO_CONTACT').'</strong></p><br/>';
}

/**
 * Helper Functions
 */

function formatDate($date)
{
	return $date ? implode('.', array_reverse(explode('-', $date))) : null;
}

function initializePdf($title)
{
	$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
	$pdf->SetCreator(PDF_CREATOR);
	$pdf->SetAuthor(PDF_AUTHOR);
	$pdf->SetTitle($title);
	$pdf->setPrintHeader(false);
	$pdf->setPrintFooter(false);
	$pdf->SetMargins(15, 30, 15);
	$pdf->SetAutoPageBreak(true, 30);
	$pdf->SetDisplayMode('real', 'OneColumn');
	$pdf->AddPage();
	return $pdf;
}

function addPage($contactid, $quoteid, $quotedate, $website, $template, $translate, $pdf)
{
	$pdf->AddPage();
}

function addLogo($x, $y, $width, $website, $template, $pdf)
{
	if(isset($template) && $template['logo'] && file_exists(BASE_PATH.'/files/images/'.$template['logo'])) {
		$logo = BASE_PATH.'/files/images/'.$template['logo'];
		$pdf->Image($logo, $x, $y, $width, 0, '', $website);
	}
}

function positions($positions, $attributesByGroup, $settings, $pdf) {
	$y = 0;
	$i = 1;
	$a = 1;
	$positionsArray = array();
	$childsArray = array();
	foreach($positions as $position) {
		$positionsArray[$position->id] = $position;
		$childsArray[$position->masterid][] = $position->id;
	}
	foreach($positions as $position) {
		if($position->masterid == 0) {
			if($settings['displayPrices']) {
				$x = $pdf->getX();
				$pdf->setCellPaddings(0, 2, 0, 0);
				$pdf->SetFont('freesans', '', 9);
				$pdf->MultiCell(10, 0, $i, 0, 'C', false, 0, $x, '', true, 0);
				$pdf->MultiCell(10, 0, $position->quantity, 0, 'C', false, 0, $x+108, '', true, 0);
				if($position->uom) $pdf->MultiCell(12, 0, $position->uom, 0, 'C', false, 0, $x+118, '', true, 0);
				$pdf->MultiCell(25, 0, $position->price, 0, 'C', false, 0, $x+130, '', true, 0);
				$pdf->MultiCell(25, 0, $position->total, 0, 'C', false, 0, $x+155, '', true, 0);
				if($position->sku) $pdf->MultiCell(108, 0, $position->sku, 0, 'L', false, 2, $x+10, '', true, 0);
				$pdf->setCellPaddings(0, 0, 0, 0);
				if($position->title) {
					$pdf->MultiCell(108, 0, $position->title, 0, 'L', false, 2, $x+10, '', true, 0);
				}
				if($position->image && file_exists(BASE_PATH.'/files/images/'.$position->image)) {
					$startPage = $pdf->getPage();
					$y = $pdf->getY();
					$pdf->Image(BASE_PATH.'/files/images/'.$position->image, $x+10, '', 30, 0, '', '', 'N');
					$endPage = $pdf->getPage();
					if($startPage == $endPage) {
						$imageHeight = $pdf->getY() - $y;
					} else {
						$imageHeight = $pdf->getY() + $pdf->getPageHeight() - $y - 60;
						$pdf->setPage($startPage);
					}
					if($position->description) {
						$pdf->MultiCell(65, $imageHeight, $position->description, 0, 'L', false, 1, $x+43, $y, true, 0);
					}
				} elseif($position->description) {
					$pdf->MultiCell(98, 0, $position->description, 0, 'L', false, 1, $x+10, '', true, 0);
				}

				// Display attributes
				if (isset($attributesByGroup[$position->id])) {
					if (!$position->description) {
						foreach ($attributesByGroup[$position->id] as $attributeSet) {
							// Add a top margin before each attribute set title
							$currentY = $pdf->GetY();
							$margin = 5; // Set your desired margin size
							$pdf->SetY($currentY + $margin);
							$pdf->SetFont('freesans', 'B', 9);
							$pdf->MultiCell(108, 0, $attributeSet['title'], 0, 'L', false, 2, $x + 10, '', true, 0);
							$pdf->SetFont('freesans', '', 9);
							foreach ($attributeSet['attributes'] as $attribute) {
								$pdf->MultiCell(108, 0, $attribute['title'] . ': ' . $attribute['description'], 0, 'L', false, 2, $x + 10, '', true, 0);
							}
						}
					}
				}

				$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-2, true, 0);
				++$i;
				if(isset($childsArray[$position->id])) {
					foreach($childsArray[$position->id] as $child) {
						childPositions($positionsArray[$child], $settings, $pdf, $i);
						++$i;
					}
				}
			} else {
				$x = $pdf->getX();
				$pdf->setCellPaddings(0, 2, 0, 0);
				$pdf->SetFont('freesans', '', 9);
				$pdf->MultiCell(10, 0, $i, 0, 'C', false, 0, $x, '', true, 0);
				if($position->sku) $pdf->MultiCell(25, 0, $position->sku, 0, 'C', false, 0, $x+10, '', true, 0);
				if($position->title) {
					if($position->image && file_exists(BASE_PATH.'/files/images/'.$position->image)) {
						$pdf->MultiCell(95, 0, $position->title, 0, 'L', false, 0, $x+68, '', true, 0);
					} else {
						$pdf->MultiCell(95, 0, $position->title, 0, 'L', false, 0, $x+35, '', true, 0);
					}
				}
				$pdf->MultiCell(25, 0, $position->quantity, 0, 'C', false, 0, $x+130, '', true, 0);
				if($position->uom) $pdf->MultiCell(25, 0, $position->uom, 0, 'C', false, 0, $x+155, '', true, 0);
				$pdf->setCellPaddings(0, 0, 0, 0);
				if($position->image && file_exists(BASE_PATH.'/files/images/'.$position->image)) {
					$startPage = $pdf->getPage();
					$y = $pdf->getY() + 2;
					$pdf->Image(BASE_PATH.'/files/images/'.$position->image, $x+35, $y, 30, 0, '', '', 'N');
					$endPage = $pdf->getPage();
					if($startPage == $endPage) {
						$imageHeight = $pdf->getY() - $y;
					} else {
						$imageHeight = $pdf->getY() + $pdf->getPageHeight() - $y - 60;
						$pdf->setPage($startPage);
					}
					if($position->description) {
						if($position->title) {
							$pdf->MultiCell(62, $imageHeight-2, $position->description, 0, 'L', false, 1, $x+68, $y+4, true, 0);
						} else {
							$pdf->MultiCell(62, $imageHeight+2, $position->description, 0, 'L', false, 1, $x+68, $y, true, 0);
						}
					}
				} elseif($position->description) {
					if($position->title) $pdf->ln(4);
					$pdf->MultiCell(95, 0, $position->description, 0, 'L', false, 1, $x+35, $pdf->getY()+2, true, 0);
				}
				$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-4, true, 0);
				++$i;
				if(isset($childsArray[$position->id])) {
					foreach($childsArray[$position->id] as $child) {
						childPositions($positionsArray[$child], $settings, $pdf, $i);
						++$i;
					}
				}
			}
		}
		++$a;
	}
	$pdf->ln(4);
}

function positionsHeader($settings, $pdf, $translate) {
	if($settings['displayPrices']) {
		$pdf->Cell(10, 5, $translate('DOCUMENTS_POSITION'), 'LTB');
		$pdf->setCellPaddings(0, 0, 0, 0);
		$pdf->Cell(98, 5, $translate('DOCUMENTS_DESCRIPTION'), 'TB');
		$pdf->Cell(10, 5, $translate('DOCUMENTS_QUANTITY'), 'TB');
		$pdf->Cell(12, 5, $translate('DOCUMENTS_UOM'), 'TB', 0, 'C');
		$pdf->Cell(25, 5, $translate('DOCUMENTS_PRICE_SINGLE'), 'TB', 0, 'C');
		$pdf->Cell(25, 5, $translate('DOCUMENTS_PRICE_TOTAL'), 'TBR', 0, 'C');
	} else {
		$pdf->Cell(10, 5, $translate('DOCUMENTS_POSITION'), 'LTB');
		$pdf->setCellPaddings(0, 0, 0, 0);
		$pdf->Cell(25, 5, $translate('DOCUMENTS_SKU'), 'TB', 0, 'C');
		$pdf->Cell(95, 5, $translate('DOCUMENTS_DESCRIPTION'), 'TB', 0, 'L');
		$pdf->Cell(25, 5, $translate('DOCUMENTS_QUANTITY'), 'TB', 0, 'C');
		$pdf->Cell(25, 5, $translate('DOCUMENTS_UOM'), 'TBR', 0, 'C');
	}
	$pdf->ln(5);
}

function childPositions($position, $settings, $pdf, $i) {
	if($settings['displayPrices']) {
		$x = $pdf->getX();
		$pdf->setCellPaddings(0, 2, 0, 0);
		$pdf->SetFont('freesans', '', 9);
		$pdf->MultiCell(10, 0, $i, 0, 'C', false, 0, $x, '', true, 0);
		$pdf->MultiCell(10, 0, $position->quantity, 0, 'C', false, 0, $x+108, '', true, 0);
		if($position->uom) $pdf->MultiCell(12, 0, $position->uom, 0, 'C', false, 0, $x+118, '', true, 0);
		$pdf->MultiCell(25, 0, $position->price, 0, 'C', false, 0, $x+130, '', true, 0);
		$pdf->MultiCell(25, 0, $position->total, 0, 'C', false, 0, $x+155, '', true, 0);
		if($position->sku) $pdf->MultiCell(108, 0, $position->sku, 0, 'L', false, 2, $x+10, '', true, 0);
		$pdf->setCellPaddings(0, 0, 0, 0);
		if($position->title) {
			$pdf->MultiCell(108, 0, $position->title, 0, 'L', false, 2, $x+10, '', true, 0);
		}
		if($position->image && file_exists(BASE_PATH.'/files/images/'.$position->image)) {
			$startPage = $pdf->getPage();
			$y = $pdf->getY();
			$pdf->Image(BASE_PATH.'/files/images/'.$position->image, $x+10, '', 30, 0, '', '', 'N');
			$endPage = $pdf->getPage();
			if($startPage == $endPage) {
				$imageHeight = $pdf->getY() - $y;
			} else {
				$imageHeight = $pdf->getY() + $pdf->getPageHeight() - $y - 60;
				$pdf->setPage($startPage);
			}
			if($position->description) {
				$pdf->MultiCell(65, $imageHeight, $position->description, 0, 'L', false, 1, $x+43, $y, true, 0);
			}
		} elseif($position->description) {
			$pdf->MultiCell(98, 0, $position->description, 0, 'L', false, 1, $x+10, '', true, 0);
		}
		$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-2, true, 0);
		++$i;
	} else {
		$x = $pdf->getX();
		$pdf->setCellPaddings(0, 2, 0, 0);
		$pdf->SetFont('freesans', '', 9);
		$pdf->MultiCell(10, 0, $i, 0, 'C', false, 0, $x, '', true, 0);
		$pdf->MultiCell(25, 0, $position->quantity, 0, 'C', false, 0, $x+130, '', true, 0);
		if($position->uom) $pdf->MultiCell(25, 0, $position->uom, 0, 'C', false, 0, $x+155, '', true, 0);
		$pdf->MultiCell(108, 0, $position->title, 0, 'L', false, 0, $x+35, '', true, 0);
		if($position->sku) $pdf->MultiCell(25, 0, $position->sku, 0, 'C', false, 2, $x+10, '', true, 0);
		$pdf->setCellPaddings(0, 0, 0, 0);
		if($position->image && file_exists(BASE_PATH.'/files/images/'.$position->image)) {
			$startPage = $pdf->getPage();
			$y = $pdf->getY();
			$pdf->Image(BASE_PATH.'/files/images/'.$position->image, $x+10, '', 30, 0, '', '', 'N');
			$endPage = $pdf->getPage();
			if($startPage == $endPage) {
				$imageHeight = $pdf->getY() - $y;
			} else {
				$imageHeight = $pdf->getY() + $pdf->getPageHeight() - $y - 60;
				$pdf->setPage($startPage);
			}
			if($position->description) {
				$pdf->MultiCell(65, $imageHeight, $position->description, 0, 'L', false, 1, $x+43, $y, true, 0);
			}
		} elseif($position->description) {
			$pdf->MultiCell(98, 0, $position->description, 0, 'L', false, 1, $x+35, '', true, 0);
		}
		$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-2, true, 0);
		++$i;
	}
}

function removeImages($html) {
	// Create a new DOMDocument instance
	$doc = new DOMDocument();

	// Suppress warnings from invalid HTML
	libxml_use_internal_errors(true);

	// Ensure the HTML is properly encoded
	$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');

	// Load the HTML
	$doc->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);

	// Restore error handling
	libxml_clear_errors();

	// Get all <img> tags
	$images = $doc->getElementsByTagName('img');

	// Remove all <img> tags
	while ($images->length > 0) {
		$img = $images->item(0);
		$img->parentNode->removeChild($img);
	}

	// Get the updated HTML
	$updatedHtml = $doc->saveHTML();

	return $updatedHtml;
}

function footer($footer, $pdf) {
	$pdf->SetFont('freesansb', '', 9);
	$pdf->MultiCell(165, 0, $footer, 0, 'L', false, 0, '', '', $reseth=true, $stretch=0, $ishtml=true);

	$pdf->setCellPaddings(3, 1, 3, 1);

	$pdf->SetFont('freesansb', 'B', 10);
}

function options($positions, $options, $optionSets, $settings, $pdf) {
	$y = 0;
	$list = array();
	$addPage = true;
	foreach($positions as $position) {
		$list[] = $position->sku;
		if(isset($options[$position->id]) && $addPage) {
			$pdf->AddPage();
			$pdf->SetFont('freesans', 'B', 9);
			$pdf->setCellPaddings(1, 2, 1, 2);
			$pdf->MultiCell(175, 0, "-------------------------------------------------------------------------------------------------------------------------------------------------------------------", 0, 'L', false, 1, '', '', true, 0);
			$pdf->MultiCell(175, 0, "Folgende Ausstattungen und Funktionen die nicht im Angebot enthalten sind können je nach Bedarf und Einsatzzweck der Maschine zusätzlich bestellt werden. Die Basismaschine in der Grundausstattung ist einsatzfähig und betriebsbereit.", 0, 'L', false, 1, '', '', true, 0);
			$pdf->MultiCell(175, 0, "-------------------------------------------------------------------------------------------------------------------------------------------------------------------", 0, 'L', false, 1, '', '', true, 0);
			$pdf->setCellPaddings(1, 1, 1, 1);
			$addPage = false;
		}
	}
	foreach($positions as $position) {
		if(isset($options[$position->id])) {
			$pdf->SetFont('freesans', 'B', 10);
			$pdf->MultiCell(175, 0, 'Optionale Ausstattung für '.$position->sku.' '.$position->title, 0, 'L', false, 1, '', '', true, 0);
			foreach($optionSets[$position->id] as $optionSet) {
				if($pdf->getY() > 250) $pdf->AddPage();
				$pdf->SetFont('freesans', 'B', 10);
				$pdf->MultiCell(145, 0, $optionSet->title, 0, 'L', false, 0, '', '', true, 0);
				$pdf->MultiCell(30, 0, "- optional -", 0, 'R', false, 1, '', '', true, 0);
				$pdf->SetFont('freesans', '', 9);
				foreach($options[$position->id][$optionSet->id] as $option) {
					if(($option->price != 0) && (array_search($option->sku, $list) == false)) {
						$pdf->MultiCell(15, 0, $option->sku, 0, 'L', false, 0, '', '', true, 0);
						$pdf->MultiCell(130, 0, $option->title, 0, 'L', false, 0, '', '', true, 0);
						if($option->price == 0) $option->price = 'bereits enthalten';
						elseif($option->price == -1) $option->price = 'auf Anfrage';
						elseif($option->price == -2) $option->price = 'nicht Verfügbar';
						$pdf->MultiCell(30, 0, $option->price, 0, 'R', false, 1, 160, '', true, 0);
						if($option->description) $pdf->MultiCell(120, 0, $option->description, 0, 'L', false, 1, 30, '', true, 0);
					}
				}
			}
			$pdf->MultiCell(0, 5, ' ', 'B', 'L', false, 1, '', $pdf->getY()-2, true, 0);
			$pdf->setY($pdf->getY()+2);
		}
	}
}

function totalBox($pdf, $positions, $settings, $document, $translate) {
	$x = 120;
	$y = $pdf->getY();
	$pdf->SetFont('freesansb', 'B', 10);
	$pdf->setCellPaddings(3, 1, 3, 1);
	$pdf->MultiCell(45, 0, $translate('DOCUMENTS_SUBTOTAL'), 'LT', 'L', false, 0 ,$x);
	$pdf->MultiCell(30, 0, $document['subtotal'], 'TR', 'R', false, 1);
	$pdf->setCellPaddings(3, 0, 3, 1);
	$pdf->MultiCell(45, 0, $translate('DOCUMENTS_TAXES').' ('.$document['taxrate'].'%)', 'L', 'L', false, 0 ,$x);
	$pdf->MultiCell(30, 0, $document['taxes'], 'R', 'R', false, 1);
	$pdf->setCellPaddings(3, 1, 3, 1);
	$pdf->MultiCell(45, 0, $translate('DOCUMENTS_TOTAL'), 'LBT', 'L', false, 0 ,$x);
	$pdf->MultiCell(30, 0, $document['total'], 'RBT', 'R', false, 1);
	if(isset($document['prepayment']) && $document['prepayment']) {
		$pdf->MultiCell(45, 0, $translate('DOCUMENTS_PREPAYMENT'), 'L', 'L', false, 0 ,$x);
		$pdf->MultiCell(30, 0, '- '.$document['prepayment'], 'R', 'R', false, 1);
		$pdf->MultiCell(45, 0, $translate('DOCUMENTS_BALANCE'), 'LB', 'L', false, 0 ,$x);
		$pdf->MultiCell(30, 0, $document['balance'], 'RB', 'R', false, 1);
	}
	$page = $pdf->getPage();
	$pdf->setY($y);
}

function sample($pdf, $txt) {
	// set alpha to semi-transparency
	$pdf->SetAlpha(0.5);
	$pdf->SetTextColor(225, 225, 225);
	$y = $pdf->GetY();
	$width = $pdf->GetX();
	$pdf->setY(140);
	$pdf->SetFont('helvetica', 'B', 75);
	$pdf->Write(0, $txt, '', false, 'C');
	//$pdf->Cell(0, 200, $txt, 0, false, 'C', 0, '', 0, false, 'T', 'M');
	$pdf->SetY($y);
	$pdf->setX($width);
	$pdf->SetTextColor(0, 0, 0);
	// restore full opacity
	$pdf->SetAlpha(1);
}

function cancelled($pdf, $txt) {
	// set alpha to semi-transparency
	$pdf->SetAlpha(0.5);
	$pdf->SetTextColor(225, 225, 225);
	$y = $pdf->GetY();
	$width = $pdf->GetX();
	$pdf->setY(140);
	$pdf->SetFont('helvetica', 'B', 75);
	$pdf->Write(0, $txt, '', false, 'C');
	$pdf->SetY($y);
	$pdf->setX($width);
	$pdf->SetTextColor(0, 0, 0);
	// restore full opacity
	$pdf->SetAlpha(1);
}
