<?php
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);

echo $this->Messages();
echo $this->FileManager();

echo $this->form->renderForm([
	'id' => 'user',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => [
			'title' => 'TABS_OVERVIEW',
			'cols' => [
				[
					'class' => 'col-sm-12 col-lg-7',
					'fields' => [
						'id',
						'username',
						'name',
						'email',
						[
							'html' => '<dt id="password-label"><label>'.$this->translate('USERS_PASSWORD').'</label></dt>
								<dd><button name="password" id="password" type="button" class="password poplight" rel="newPassword">Neues Passwort</button></dd>',
						],
					],
				],
			],
		],
		'smtp' => [
			'title' => 'USERS_MAIL_SETTINGS',
			'cols' => [
				[
					'class' => 'col-sm-12 col-lg-7',
					'fields' => [
						'emailsender',
						'smtphost',
						'smtpauth',
						'smtpsecure',
						'smtpuser',
						'smtppass',
					],
				],
			],
		],
	],
]);
?>

<div id="popup">
	<div id="newPassword" class="popup_block">
		<iframe src="<?php echo $this->url(['module' => 'users', 'controller' => 'user', 'action' => 'password']); ?>" width="100%" height="100%"></iframe>
	</div>
</div>
