<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->FileManager();
?>

<ul class="tabs">
	<li><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content">
		<form id="user" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-7">
					<dl class="form">
						<?php echo $this->form->getElement('id') ?>
						<?php echo $this->form->getElement('username') ?>
						<?php echo $this->form->getElement('name') ?>
						<?php echo $this->form->getElement('email') ?>
						<dt id="password-label"><label><?php echo $this->translate('USERS_PASSWORD'); ?></label></dt>
						<dd>
							<button name="password" id="password" type="button" class="password poplight" rel="newPassword">Neues Passwort</button>
						</dd>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-5">
					<h4><?php echo $this->translate('USERS_MAIL_SETTINGS') ?></h4>
					<?php echo $this->form->getElement('smtphost') ?>
					<?php echo $this->form->getElement('smtpauth') ?>
					<?php echo $this->form->getElement('smtpsecure') ?>
					<?php echo $this->form->getElement('smtpuser') ?>
					<?php echo $this->form->getElement('smtppass') ?>
				</div>
			</div>
		</form>
	</div>
</div>

<div id="popup">
	<div id="newPassword" class="popup_block">
		<iframe src="<?php echo $this->url(array('module'=>'users', 'controller'=>'user', 'action'=>'password'));?>" width="100%" height="100%"></iframe>
	</div>
</div>
