<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->FileManager();
?>

<ul class="tabs">
	<li><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content">
		<form id="item" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="row">
                <div class="col-sm-12 col-lg-7">
				    <dl class="form">
					    <?php echo $this->form->getElement('id') ?>
					    <?php echo $this->form->getElement('username') ?>
					    <?php echo $this->form->getElement('name') ?>
					    <?php echo $this->form->getElement('email') ?>
				    </dl>
		        </div>
                <div class="col-sm-12 col-lg-5">
                    <h4><?php echo $this->translate('USERS_MAIL_SETTINGS') ?></h4>
				    <?php echo $this->form->getElement('smtphost') ?>
				    <?php echo $this->form->getElement('smtpauth') ?>
				    <?php echo $this->form->getElement('smtpsecure') ?>
				    <?php echo $this->form->getElement('smtpuser') ?>
				    <?php echo $this->form->getElement('smtppass') ?>
			    </div>
		    </div>
		</form>
	</div>
</div>
