<?php 
$this->title = $this->translate('USERS_PASSWORD');
$this->headTitle($this->title);
echo $this->Messages();
?>

<form id="password" enctype="application/x-www-form-urlencoded" action="" method="post">
	<dl class="form">
		<p>Legen Sie ein starkes Kennwort fest, um den unbefugten Zugriff auf Ihr Konto zu verhindern.</p>
		<?php echo $this->form->getElement('passwordactual') ?>
		<?php echo $this->form->getElement('passwordnew') ?>
		<p>Nutzen Sie mindestens 8 Zeichen</p>
		<?php echo $this->form->getElement('passwordconfirm') ?>
		<dt id="password-label"><label></label></dt>
		<dd>
			<button name="password" id="password" type="button" class="password" onclick="save()">Passwort ändern</button>
		</dd>
	</dl>
</form>
