<?php
$this->title = $this->translate('ADMIN_MODULES');
$this->headTitle($this->title);
echo $this->Messages();
?>

<div class="row">
	<div class="col-sm-4 col-lg-2">
		<?php echo $this->AdminMenu(); ?>
	</div>
	<div class="col-sm-8 col-lg-10">
		<table id="data">
			<thead>
				<tr>
					<th width="2%">
						<?php if($this->user['admin']) : ?>
							<input type="checkbox" class="checkall" name="checkall"/>
						<?php endif; ?>
					</th>
					<th class="id" width="5%">
						<?php echo $this->translate('ADMIN_ID'); ?>
					</th>
					<th class="name" width="20%">
						<?php echo $this->translate('ADMIN_NAME'); ?>
					</th>
					<th class="menu" width="20%">
						<?php echo $this->translate('ADMIN_MENU'); ?>
					</th>
					<th class="ordering" width="20%">
						<?php echo $this->translate('ADMIN_ORDERING'); ?>
					</th>
					<th class="active" width="20%">
						<?php echo $this->translate('ADMIN_ACTIVE'); ?>
					</th>
					<th width="8%"></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->modules as $module) : ?>
					<tr>
						<td>
							<?php if($this->user['admin']) : ?>
								<input class="id" type="checkbox" value="<?php echo $module->id ?>" name="id"/>
							<?php else : ?>
								<input class="id" type="hidden" value="<?php echo $module->id ?>" name="id"/>
							<?php endif; ?>
						</td>
						<td class="id">
							<?php echo $this->escape($module->id); ?>
						</td>
						<td class="name">
							<span class="editable" data-name="name"><?php echo $this->escape($module->name); ?></span>
						</td>
						<td class="name">
							<pre class="editable" data-name="menu" data-type="textarea"><?php echo $this->escape($module->menu); ?></pre>
						</td>
						<td class="name">
							<span class="editable" data-name="ordering"><?php echo $this->escape($module->ordering); ?></span>
						</td>
						<td class="name">
							<span class="editable" data-name="active"><?php echo $this->escape($module->active); ?></span>
						</td>
						<td class="buttons">
							<?php echo $this->Button('copy'); ?>
							<?php echo $this->Button('delete'); ?>
						</td>
					</tr>
				<?php endforeach; ?>
				<tr class="add">
					<td>
					</td>
					<td>
						<?php echo $this->translate('TOOLBAR_NEW'); ?>
					</td>
					<td>
						<?php echo $this->form->name; ?>
					</td>
					<td>
						<?php echo $this->form->menu; ?>
					</td>
					<td>
						<?php echo $this->form->ordering; ?>
					</td>
					<td>
						<?php echo $this->form->active; ?>
					</td>
					<td class="buttons">
						<?php echo $this->toolbar->save; ?>
						<?php //echo $this->toolbar->cancel; ?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
