<?php
$i = 1;
if($length = count($this->forms)) :
?>
<table id="positions" class="noheader" width="100%">
	<tbody>
		<?php foreach($this->forms as $form) :
			if($form->getValue('itemtype') == 'stockItem') $rowspan = 2;
			elseif($form->getValue('itemtype') == 'deliveryItem') $rowspan = 2;
			else $rowspan = 1;
		?>
		<tr class="position<?php echo $form->getValue('id'); ?>">
			<td class="id" rowspan ="<?php echo $rowspan; ?>">
				<input class="id" type="checkbox" value="<?php echo $form->getValue('id'); ?>" name="id"/>
			</td>
			<td class="ordering" rowspan ="<?php echo $rowspan; ?>">
				<?php echo $form->ordering; ?>
			</td>
			<td>
				<?php echo $form->itemtype; ?>
			</td>
			<td>
				<?php echo $form->sku; ?>
			</td>
			<td>
				<?php echo $form->title; ?>
			</td>
			<td>
				<?php echo $form->uom; ?>
			</td>
			<td>
				<?php echo $form->quantity; ?>
			</td>
			<td>
				<?php echo $form->price; ?>
			</td>
			<td>
				<?php echo $form->shippingmethod; ?>
			</td>
			<td class="deliverydate">
				<?php echo $form->deliverydate; ?>
			</td>
			<td class="deliverystatus  <?php echo $form->getValue('deliverystatus'); ?>">
				<?php echo $form->deliverystatus; ?>
			</td>
			<td class="notes" rowspan ="<?php echo $rowspan; ?>">
				<?php echo $form->notes; ?>
			</td>
			<td class="buttons" rowspan ="<?php echo $rowspan; ?>">
				<?php echo $this->toolbar->delete->setLabel(''); ?>
				<?php echo $this->toolbar->copy->setLabel(''); ?>
				<?php if($i>1) : ?>
					<?php echo $this->toolbar->sortup; ?>
				<?php endif; ?>
				<?php if($i<$length) : ?>
					<?php echo $this->toolbar->sortdown; ?>
				<?php endif; ?>
			</td>
		</tr>
		<!--<tr class="position<?php echo $form->getValue('id'); ?> deliveryDetails">
			<td class="deliverystatus  <?php echo $form->getValue('deliverystatus'); ?>">
				<input class="id" type="hidden" value="<?php echo $form->getValue('id'); ?>" name="id"/>
			</td>
			<td>
				<?php //echo $form->shipmentdate; ?>
			</td>
			<td colspan="5">
				<?php //echo $form->shipmentnumber; ?>
			</td>
		</tr>-->
		<tr class="position<?php echo $form->getValue('id'); ?> stockItem"<?php if($form->getValue('itemtype') != "stockItem") echo ' style="display:none"'; ?>>
			<td>
				<input class="id" type="hidden" value="<?php echo $form->getValue('id'); ?>" name="id"/>
			</td>
			<td></td>
			<td>
				<?php echo $form->deliveryorderid; ?>
			</td>
			<td>
				<?php echo $form->deliveryorderdate; ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr class="position<?php echo $form->getValue('id'); ?> deliveryItem"<?php if($form->getValue('itemtype') != "deliveryItem") echo ' style="display:none"'; ?>>
			<!--<td>
				<input class="id" type="hidden" value="<?php echo $form->getValue('id'); ?>" name="id"/>
				<b><?php echo $this->translate('PROCESSES_SUPPLIER_DATA'); ?></b>
			</td>-->
			<td></td>
			<td></td>
			<td>
				<?php echo $form->supplierid; ?>
			</td>
			<td>
				<?php echo $form->suppliername; ?>
			</td>
			<td>
				<?php echo $form->purchaseorderid; ?>
			</td>
			<td>
				<?php echo $form->purchaseorderdate; ?>
			</td>
			<td>
				<?php echo $form->suppliersalesorderid; ?>
			</td>
			<td>
				<?php echo $form->suppliersalesorderdate; ?>
			</td>
			<td>
				<?php echo $form->supplierinvoicetotal; ?>
			</td>
			<td>
				<?php echo $form->supplierpaymentdate; ?>
			</td>
			<td class="supplierorderstatus <?php echo $form->getValue('supplierorderstatus'); ?>">
				<input class="id" type="hidden" value="<?php echo $form->getValue('id'); ?>" name="id"/>
				<?php echo $form->supplierorderstatus; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
		<!--<tr class="position<?php echo $form->getValue('id'); ?> deliveryItem"<?php if($form->getValue('itemtype') != "deliveryItem") echo ' style="display:none"'; ?>>
			<td>
			</td>
			<td>
				<?php //echo $form->supplierinvoiceid; ?>
				<?php //echo $form->supplierinvoicedate; ?>
			</td>
		</tr>-->
		<?php /* ?>
		<tr class="position<?php echo $form->getValue('id'); ?> service"<?php if($form->getValue('itemtype') != "service") echo ' style="display:none"'; ?>>
			<td>
				<input class="id" type="hidden" value="<?php echo $form->getValue('id'); ?>" name="id"/>
			</td>
			<td></td>
			<td></td>
			<td>
				<?php echo $form->servicedate; ?>
			</td>
			<td colspan="2">
				<?php echo $form->serviceexecutedby; ?>
			</td>
			<td colspan="2">
			</td>
			<td>
				<?php echo $form->servicecompleted; ?>
			</td>
		</tr>
		<?php */ ?>
		<?php ++$i; ?>
	<?php endforeach; ?>
	</tbody>
</table>
<?php endif; ?>
