<?php
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('CAMPAIGNS_NEW_CAMPAIGN');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'campaign',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'contacts' => [
			'title' => 'TABS_CONTACTS',
			'html' => $this->Contacts(),
		],
		'errors' => [
			'title' => 'TABS_ERRORS',
			'html' => $this->Errors(),
		],
		'messages' => [
			'title' => 'TABS_MESSAGES',
			'html' => $this->EmailMessages(),
			'a_attrs' => [
				'data-tab-load' => 'getEmailmessages',
			],
		],
		'files' => [
			'title' => 'TABS_FILES',
			'html' => $this->Files(),
		],
	],
]); ?>
