<?php
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('CAMPAIGNS_NEW_CAMPAIGN');
$this->headTitle($this->title);
?>

<?php echo $this->form->renderForm([
	'id' => 'campaign',
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'contacts' => [
			'title' => 'TABS_CONTACTS',
			'html' => '<div id="campaign-recipients"></div>',
			'a_attrs' => [
				'data-tab-load' => 'getCampaignRecipients',
			],
		],
		'errors' => [
			'title' => 'TABS_ERRORS',
			'html' => '<div id="campaign-errors"></div>',
			'a_attrs' => [
				'data-tab-load' => 'getCampaignErrors',
			],
		],
	],
]); ?>
