<?php		 
$this->title = $this->translate('INVOICES');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="invoiceid" width="5%">
				<?php echo $this->translate('INVOICES_INVOICE_ID'); ?>
			</th>
			<th class="title" width="24%">
				<?php echo $this->translate('INVOICES_TITLE'); ?>
			</th>
			<th class="contactid" width="5%">
				<?php echo $this->translate('INVOICES_CONTACT'); ?>
			</th>
			<th class="billingaddress" width="20%">
				<?php echo $this->translate('INVOICES_BILLING_ADDRESS'); ?>
			</th>
			<th class="notes" width="15%">
				<?php echo $this->translate('INVOICES_NOTES') ?>
			</th>
			<th class="invoicedate" width="8%">
				<?php echo $this->translate('INVOICES_INVOICE_DATE'); ?>
			</th>
			<th class="deliverydate" width="8%">
				<?php echo $this->translate('INVOICES_DELIVERY_DATE'); ?>
			</th>
			<th class="total" width="8%">
				<?php echo $this->translate('INVOICES_TOTAL'); ?>
			</th>
			<th class="state" width="6%">
				<?php echo $this->translate('INVOICES_STATE'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->invoices as $invoice) : ?>
		<tr class="state<?php echo $invoice->state; ?><?php echo $invoice->pinned ? ' pinned' : ''; ?>">
			<td><input class="id" type="checkbox" value="<?php echo $invoice->id ?>" name="id"/></td>
			<td class="invoiceid">
				<?php if($invoice->invoiceid) : ?>
					<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'invoice', 'action'=>'edit', 'id'=>$invoice->id)); ?>">
						<?php echo $this->escape($invoice->invoiceid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_TITLE') ?>" class="title">
				<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'invoice', 'action'=>'edit', 'id'=>$invoice->id)); ?>">
					<?php echo $invoice->title ? $this->escape($invoice->title) : $this->translate('INVOICE')." ".$this->escape($invoice->invoiceid); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_CONTACT') ?>" class="contactid">
				<?php if($invoice->contactid) : ?>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$invoice->cid)); ?>">
						<?php echo $this->escape($invoice->contactid); ?><br/>
						<?php echo $this->escape($invoice->billingname1); ?>
						<?php if($invoice->billingname2) echo "<br/>".$this->escape($invoice->billingname2); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_BILLING_ADDRESS') ?>" class="billingaddress">
				<?php echo $this->escape($invoice->billingstreet); ?><br/>
				<?php echo $this->escape($invoice->billingpostcode); ?><br/>
				<?php echo $this->escape($invoice->billingcity); ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_NOTES') ?>" class="notes">
				<?php if($invoice->notes) : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $invoice->notes; ?>" data-type="textarea"><?php echo $invoice->notes; ?></pre>
				<?php else : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $invoice->notes; ?>" data-type="textarea" data-empty="true"><?php echo $this->translate('TOOLBAR_NEW') ;?></pre>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_INVOICE_DATE') ?>" class="invoicedate">
				<?php if($invoice->invoicedate) echo $this->escape(date("d.m.Y", strtotime($invoice->invoicedate))); ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_DELIVERY_DATE') ?>" class="deliverydate">
				<?php if($invoice->deliverydate) echo $this->escape(date("d.m.Y", strtotime($invoice->deliverydate))); ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_TOTAL') ?>" class="total">
				<?php echo $this->escape($invoice->total); ?>
			</td>
			<td data-label="<?php echo $this->translate('INVOICES_STATE') ?>" class="state">
				<?php if($invoice->state == '105' || $invoice->state == '106') : ?>
					<?php echo $this->translate($this->escape($this->options['states'][$invoice->state])); ?>
				<?php else : ?>
					<span class="editable" data-name="state" data-value="<?php echo $invoice->state; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['states'][$invoice->state])); ?></span>
				<?php endif; ?>
			</td>
			<td class="pin">
				<?php if($invoice->pinned) : ?>
					<input type = "button" onclick = "pin(<?php echo $invoice->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
				<?php else : ?>
					<input type = "button" onclick = "pin(<?php echo $invoice->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
				<?php endif; ?>
			</td>
			<td class="buttons">
				<?php if($invoice->state == '105' || $invoice->state == '106') : ?>
					<?php echo $this->toolbar->viewInline; ?>
				<?php else : ?>
					<?php echo $this->toolbar->editInline; ?>
				<?php endif; ?>
				<?php echo $this->toolbar->copyInline; ?>
				<?php echo $this->toolbar->pdfInline; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td></td>
			<td class="toolbar">
				<?php echo $this->ToolbarBottom(); ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="total">
				<?php echo $this->invoices->total; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
