ALTER TABLE `deliveryorder` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `deliveryorder` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `deliveryorderdate`;
ALTER TABLE `invoice` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `creditnote` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `creditnote` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `creditnote` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `creditnotedate`;
ALTER TABLE `reminder` CHANGE `opportunityid` `invoiceid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `reminder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `reminderdate`;
ALTER TABLE `salesorder` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `salesorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `quote` DROP `opportunityid`;
ALTER TABLE `invoice` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `invoiceid`;
ALTER TABLE `invoice` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `invoicedate`;
ALTER TABLE `deliveryorder` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `deliveryorderid`;
ALTER TABLE `deliveryorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `deliveryorderdate`;
ALTER TABLE `quoterequest` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `quoterequest` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `quoterequestdate`;
ALTER TABLE `purchaseorder` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `purchaseorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `purchaseorderdate`;
ALTER TABLE `invoice` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `quoterequest` ADD `salesorderid` INT(11) NOT NULL DEFAULT '0' AFTER `quoteid`;
ALTER TABLE `quoterequest` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `purchaseorder` ADD `salesorderid` INT(11) NOT NULL DEFAULT '0' AFTER `quoteid`;
ALTER TABLE `purchaseorder` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `deliveryorder` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `deliveryorder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `creditnote` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `creditnoteid`;
ALTER TABLE `creditnote` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `creditnotedate`;
ALTER TABLE `creditnote` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `quoterequest` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `quoterequest` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `purchaseorder` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `purchaseorder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `invoice` ADD `deliveryorderid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `invoice` ADD `deliveryorderdate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `purchaseorder` ADD `quoterequestid` INT(11) NOT NULL DEFAULT '0' AFTER `invoiceid`;
ALTER TABLE `purchaseorder` ADD `quoterequestdate` DATE NULL DEFAULT NULL AFTER `invoicedate`;
ALTER TABLE `emailtemplate` ADD `userid` INT(11) NOT NULL AFTER `id`;
ALTER TABLE `user` ADD `logintime` DATETIME NULL DEFAULT NULL AFTER `modifiedby`;
ALTER TABLE `inventory` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `doctype`;
ALTER TABLE `inventory` ADD `salesorderid` INT(11) NOT NULL DEFAULT '0' AFTER `quoteid`;
ALTER TABLE `inventory` CHANGE `invoiceid` `invoiceid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `inventory` CHANGE `creditnoteid` `creditnoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `inventory` ADD `deliveryorderid` INT(11) NOT NULL DEFAULT '0' AFTER `creditnoteid`;
ALTER TABLE `inventory` CHANGE `date` `inventorydate` DATE NULL DEFAULT NULL; 
ALTER TABLE `inventory` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `inventorydate`;
ALTER TABLE `inventory` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `inventory` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `inventory` ADD `deliveryorderdate` DATE NULL DEFAULT NULL AFTER `invoicedate`;
ALTER TABLE `inventory` ADD `orderdate` DATE NULL DEFAULT NULL AFTER `deliveryorderdate`;
ALTER TABLE `inventory` ADD `deliverydate` DATE NULL DEFAULT NULL AFTER `orderdate`;
ALTER TABLE `inventory` ADD `vatin` VARCHAR(255) NULL DEFAULT NULL AFTER `comment`;
ALTER TABLE `inventory` ADD `paymentmethod` VARCHAR(255) NULL DEFAULT NULL AFTER `vatin`;
ALTER TABLE `inventory` ADD `shippingmethod` VARCHAR(255) NULL DEFAULT NULL AFTER `paymentmethod`;
ALTER TABLE `inventory` ADD `billingname1` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingmethod`;
ALTER TABLE `inventory` ADD `billingname2` VARCHAR(255) NULL DEFAULT NULL AFTER `billingname1`;
ALTER TABLE `inventory` ADD `billingdepartment` VARCHAR(255) NULL DEFAULT NULL AFTER `billingname2`;
ALTER TABLE `inventory` ADD `billingstreet` TEXT NULL DEFAULT NULL AFTER `billingdepartment`;
ALTER TABLE `inventory` ADD `billingpostcode` VARCHAR(255) NULL DEFAULT NULL AFTER `billingstreet`;
ALTER TABLE `inventory` ADD `billingcity` VARCHAR(255) NULL DEFAULT NULL AFTER `billingpostcode`;
ALTER TABLE `inventory` ADD `billingcountry` VARCHAR(255) NULL DEFAULT NULL AFTER `billingcity`;
ALTER TABLE `inventory` ADD `shippingname1` VARCHAR(255) NULL DEFAULT NULL AFTER `billingcountry`;
ALTER TABLE `inventory` ADD `shippingname2` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingname1`;
ALTER TABLE `inventory` ADD `shippingdepartment` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingname2`;
ALTER TABLE `inventory` ADD `shippingstreet` TEXT NULL DEFAULT NULL AFTER `shippingdepartment`;
ALTER TABLE `inventory` ADD `shippingpostcode` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingstreet`;
ALTER TABLE `inventory` ADD `shippingcity` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingpostcode`;
ALTER TABLE `inventory` ADD `shippingcountry` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingcity`;
ALTER TABLE `inventory` ADD `shippingphone` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingcountry`;
ALTER TABLE `inventory` ADD `contactperson` VARCHAR(255) NULL DEFAULT NULL AFTER `shippingphone`;
ALTER TABLE `inventory` ADD `language` VARCHAR(255) NOT NULL AFTER `contactperson`;
ALTER TABLE `inventory` ADD `taxfree` TINYINT(1) NOT NULL DEFAULT 0 AFTER `language`;
ALTER TABLE `inventory` ADD `title` VARCHAR(255) NULL DEFAULT NULL AFTER `taxfree`;
ALTER TABLE `inventory` ADD `image` VARCHAR(255) NULL DEFAULT NULL AFTER `title`;
ALTER TABLE `inventory` ADD `description` TEXT NULL DEFAULT NULL AFTER `image`;
ALTER TABLE `inventory` ADD `priceruleamount` DECIMAL(12,4) NULL DEFAULT NULL AFTER `taxrate`;
ALTER TABLE `inventory` ADD `priceruleaction` VARCHAR(255) NULL DEFAULT NULL AFTER `priceruleamount`;
ALTER TABLE `inventory` ADD `currency` VARCHAR(255) NULL DEFAULT NULL AFTER `quantity`;
