ALTER TABLE `deliveryorder` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `deliveryorder` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `deliveryorderdate`;
ALTER TABLE `invoice` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `creditnote` CHANGE `opportunityid` `salesorderid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `creditnote` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `creditnote` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `creditnotedate`;
ALTER TABLE `reminder` CHANGE `opportunityid` `invoiceid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `reminder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `reminderdate`;
ALTER TABLE `salesorder` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `salesorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `quote` DROP `opportunityid`;
ALTER TABLE `invoice` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `invoiceid`;
ALTER TABLE `invoice` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `invoicedate`;
ALTER TABLE `deliveryorder` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `deliveryorderid`;
ALTER TABLE `deliveryorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `deliveryorderdate`;
ALTER TABLE `quoterequest` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `quoterequest` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `quoterequestdate`;
ALTER TABLE `purchaseorder` CHANGE `opportunityid` `quoteid` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `purchaseorder` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `purchaseorderdate`;
ALTER TABLE `invoice` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `quoterequest` ADD `salesorderid` INT(11) NOT NULL DEFAULT '0' AFTER `quoteid`;
ALTER TABLE `quoterequest` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `purchaseorder` ADD `salesorderid` INT(11) NOT NULL DEFAULT '0' AFTER `quoteid`;
ALTER TABLE `purchaseorder` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `deliveryorder` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `deliveryorder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `creditnote` ADD `quoteid` INT(11) NOT NULL DEFAULT '0' AFTER `creditnoteid`;
ALTER TABLE `creditnote` ADD `quotedate` DATE NULL DEFAULT NULL AFTER `creditnotedate`;
ALTER TABLE `creditnote` ADD `salesorderdate` DATE NULL DEFAULT NULL AFTER `quotedate`;
ALTER TABLE `quoterequest` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `quoterequest` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `purchaseorder` ADD `invoiceid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `purchaseorder` ADD `invoicedate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `invoice` ADD `deliveryorderid` INT(11) NOT NULL DEFAULT '0' AFTER `salesorderid`;
ALTER TABLE `invoice` ADD `deliveryorderdate` DATE NULL DEFAULT NULL AFTER `salesorderdate`;
ALTER TABLE `purchaseorder` ADD `quoterequestid` INT(11) NOT NULL DEFAULT '0' AFTER `invoiceid`;
ALTER TABLE `purchaseorder` ADD `quoterequestdate` DATE NULL DEFAULT NULL AFTER `invoicedate`;
ALTER TABLE `emailtemplate` ADD `userid` INT(11) NOT NULL AFTER `id`;
ALTER TABLE `user` ADD `logintime` DATETIME NULL DEFAULT NULL AFTER `modifiedby`;
