<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<a class="dw-btn"
   href="<?php echo $this->url([
	   'module' => 'admin',
	   'controller' => 'menu',
	   'action' => 'edit',
	   'id' => $this->form->getValue('menuid'),
   ], null, true); ?>">
	<?php echo $this->translate('ADMIN_BACK_TO_MENU'); ?>
</a>

<?php echo $this->form->renderForm(); ?>
