<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('QUOTE_REQUESTS_NEW_QUOTE_REQUEST');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'creditnote',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'positions' => [
			'title' => 'TABS_POSITIONS',
			'html' => $this->Positions('quoterequest'),
			'a_attrs' => [
				'data-tab-load' => 'getPositions',
				'data-parent' => 'quoterequest',
				'data-type' => 'pos',
			],
		],
		'customer' => ['title' => 'TABS_CUSTOMER'],
		'shipping' => ['title' => 'TABS_SHIPPING_ADDRESS'],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files()],
		'finish' => [
			'title' => 'TABS_FINISH',
			'html' => $this->Finish(),
			'a_attrs' => [
				'data-tab-load' => 'previewPdf',
			],
		],
	],
]); ?>
<?php echo $this->Popup(); ?>
