<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('QUOTE_REQUESTS_NEW_QUOTE_REQUEST');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<ul class="tabs">
	<li<?php if($this->activeTab == "#tabOverview") : ?> class="active"<?php endif; ?>>
		<a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW'); ?></a></li>
	<li<?php if($this->activeTab == "#tabPositions") : ?> class="active"<?php endif; ?>>
		<a href="#tabPositions" onclick="getPositions()"><?php echo $this->translate('TABS_POSITIONS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabCustomer") : ?> class="active"<?php endif; ?>>
		<a href="#tabCustomer"><?php echo $this->translate('TABS_SUPPLIER'); ?></a></li>
	<li<?php if($this->activeTab == "#tabShippingAddress") : ?> class="active"<?php endif; ?>>
		<a href="#tabShippingAddress"><?php echo $this->translate('TABS_SHIPPING_ADDRESS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabFiles") : ?> class="active"<?php endif; ?>>
		<a href="#tabFiles"><?php echo $this->translate('TABS_FILES'); ?></a></li>
	<li><a href="#tabFinish" onclick="previewPdf()"><?php echo $this->translate('TABS_FINISH'); ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content<?php if($this->activeTab == '#tabOverview' || !$this->activeTab) : ?> active<?php endif; ?>">
		<form id="quoterequest" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="row">
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <?php echo $this->form->id; ?>
					    <?php echo $this->form->title; ?>
					    <dt id="contactid-label"><label><?php echo $this->translate('QUOTE_REQUESTS_CONTACT'); ?></label></dt>
					    <dd>
						    <?php echo $this->toolbar->select; ?>
						    <input id="contactid" type="text" value="<?php echo $this->form->getValue('contactid'); ?>" size="3" readonly="readonly" name="contactid"/>
						    <input id="billingname1" type="text" value="<?php echo $this->form->getValue('billingname1'); ?>" size="20" readonly="readonly" name="billingname1"/>
					    </dd>
					    <?php echo $this->form->orderdate; ?>
					    <?php echo $this->form->deliverydate; ?>
					    <?php echo $this->form->paymentmethod; ?>
					    <?php echo $this->form->shippingmethod; ?>
					    <?php echo $this->form->opportunityid; ?>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <?php echo $this->form->info; ?>
				    </dl>
			    </div>
			</div>
            <div class="row">
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <?php echo $this->form->header; ?>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <dt id="textblock-label">
                            <label>Textbausteine-Kopftext</label>
                        </dt>
					    <dd id="textblock-element">
					        <textarea id="textblockheader" class="editor" name="textblockheader" cols="75" rows="18"><?php echo $this->textblocks['header']; ?></textarea>
					    </dd>
				    </dl>
			    </div>
		    </div>
            <div class="row">
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <?php echo $this->form->footer; ?>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-6">
				    <dl class="form">
					    <dt id="textblock-label">
                            <label>Textbausteine-Fußtext</label>
                        </dt>
					    <dd id="textblock-element">
					        <textarea id="textblockfooter" class="editor" name="textblockfooter" cols="75" rows="18"><?php echo $this->textblocks['footer']; ?></textarea>
					    </dd>
				    </dl>
			    </div>
		    </div>
		</form>
	</div>
	<div id="tabPositions" class="tab_content<?php if($this->activeTab == '#tabPositions') : ?> active<?php endif; ?>">
		<?php echo $this->ToolbarPositions(); ?>
		<div id="positions"></div>
		<?php echo $this->ToolbarPositions("bottom"); ?>
	</div>
	<div id="tabCustomer" class="tab_content<?php if($this->activeTab == '#tabCustomer') : ?> active<?php endif; ?>">
		<form id="quoterequest" enctype="application/x-www-form-urlencoded" action="" method="post">
		    <?php echo $this->toolbar->select; ?>
            <div class="row">
                <div class="col-sm-12 col-lg-7">
				    <dl class="form">
					    <?php echo $this->form->contactid; ?>
					    <?php echo $this->form->billingname1; ?>
					    <?php echo $this->form->billingname2; ?>
					    <?php echo $this->form->billingdepartment; ?>
					    <?php echo $this->form->billingstreet; ?>
					    <?php echo $this->form->billingpostcode; ?>
					    <?php echo $this->form->billingcity; ?>
					    <?php echo $this->form->billingcountry; ?>
					    <?php echo $this->form->vatin; ?>
					    <?php echo $this->form->taxfree; ?>
					    <?php if(isset($this->contact)) : ?>
						    <?php echo $this->ContactData(); ?>
					    <?php endif; ?>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-5">
				    <dl class="form">
					    <?php echo $this->form->contactinfo; ?>
				    </dl>
			    </div>
			</div>
		</form>
	</div>
	<div id="tabShippingAddress" class="tab_content<?php if($this->activeTab == '#tabShippingAddress') : ?> active<?php endif; ?>">
		<form id="quoterequest" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div id="left">
				<dl class="form">
					<?php echo $this->form->shippingname1; ?>
					<?php echo $this->form->shippingname2; ?>
					<?php echo $this->form->shippingdepartment; ?>
					<?php echo $this->form->shippingstreet; ?>
					<?php echo $this->form->shippingpostcode; ?>
					<?php echo $this->form->shippingcity; ?>
					<?php echo $this->form->shippingcountry; ?>
					<?php echo $this->form->shippingphone; ?>
				</dl>
			</div>
			<div id="right">
			</div>
		</form>
		<div style="clear:left"></div>
	</div>
	<div id="tabFiles" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
		<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?lang=de&type=0" width="100%" height="700px"></iframe>
	</div>
	<div id="tabFinish" class="tab_content">
        <form id="quoterequest" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="row">
                <div class="col-sm-6">
		            <div id="datacheck"></div>
		            <dl class="form">
			            <?php echo $this->form->templateid; ?>
			            <?php echo $this->form->language; ?>
		            </dl>
                </div>
                <div class="col-sm-12">
		            <br/>
		            <a href="#" onclick="savePdf()"><?php echo $this->translate('QUOTE_REQUESTS_SAVE_AND_BOOK'); ?></a> |
		            <a href="<?php echo $this->url(array('module'=>'purchases', 'controller'=>'quoterequest', 'action'=>'download', 'id'=>$this->form->getValue('id')));?>" target="_blank"><?php echo $this->translate('QUOTE_REQUESTS_DOWNLOAD_PDF'); ?></a>
		            <div id="output"></div>
	            </div>
            </div>
        </form>
	</div>
</div>

<div id="popup">
	<div id="addCustomer" class="popup_block">
		<?php if($this->form->getValue('contactid')) : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'contactid'=>$this->form->getValue('contactid'), 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php else : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php endif; ?>
	</div>

	<div id="selectPosition" class="popup_block">
		<iframe src="<?php echo $this->url(array('module'=>'items', 'controller'=>'item', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller.'|'.$this->form->getValue('id')));?>" width="100%" height="100%"></iframe>
	</div>
</div>
