<?php 
$this->title = $this->reminder['title'] ? $this->reminder['title'] : $this->translate('REMINDER')." ".$this->reminder['reminderid'];
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'reminder',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'positions' => ['title' => 'TABS_POSITIONS', 'html' => $this->Positions('reminder'), 'a_attrs' => ['onclick'=>"getPositions('reminder', 'pos')"]],
		'customer' => ['title' => 'TABS_CUSTOMER'],
		'shipping' => ['title' => 'TABS_SHIPPING_ADDRESS'],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files()],
		'document' => ['title' => 'TABS_DOCUMENT', 'html' => $this->Document()],
		'messages' => ['title' => 'TABS_MESSAGES', 'html' => $this->EmailMessages(), 'a_attrs' => ['onclick'=>"getEmailmessages()"]],
	],
]); ?>
