<?php
$this->title = $this->translate('STATISTICS');
$this->headTitle($this->title);
?>

<?php echo $this->translate('STATISTICS_PERIOD'); ?>: 
<?php if($this->lenght == 12) : ?>
	1 Jahr
<?php else : ?>
	<a href="<?php echo $this->url(array('module'=>'statistics', 'controller'=>'quote', 'action'=>'index', 'lenght'=>'12')); ?>">1 Jahr</a>
<?php endif; ?>
<?php if($this->lenght == 24) : ?>
	2 Jahre
<?php else : ?>
	<a href="<?php echo $this->url(array('module'=>'statistics', 'controller'=>'quote', 'action'=>'index', 'lenght'=>'24')); ?>">2 Jahre</a>
<?php endif; ?>
<?php if($this->lenght == 60) : ?>
	5 Jahre
<?php else : ?>
	<a href="<?php echo $this->url(array('module'=>'statistics', 'controller'=>'quote', 'action'=>'index', 'lenght'=>'60')); ?>">5 Jahre</a>
<?php endif; ?>

<?php if($this->customerList) : ?>
	<h3><?php echo $this->translate('STATISTICS_CUSTOMER_TOP_TEN'); ?></h3>
	<img src="<?php echo $this->baseUrl(); ?>/cache/chart/<?php echo $this->subfolder; ?>/quote-1000-600.png">

	<h3><?php echo $this->translate('STATISTICS_CUSTOMER_LIST'); ?></h3>
	<table id="data">
		<thead>
			<tr>
				<th width="2%"><input type="checkbox" class="checkall" name="checkall"></th>
				<th class="id" width="5%"><?php echo $this->translate('STATISTICS_CUSTOMER_ID'); ?></th>
				<th class="name" width="20%"><?php echo $this->translate('STATISTICS_CUSTOMER_NAME'); ?></th>
				<th class="phone" width="12%"><?php echo $this->translate('STATISTICS_TURNOVER'); ?></th>
				<th class="phone" width="12%"><?php echo $this->translate('STATISTICS_QUOTE_QUANTITY'); ?></th>
				<th class="phone" width="12%"><?php echo $this->translate('STATISTICS_CUSTOMER_SHARE'); ?></th>
				<th width="8%"></th>
			</tr>
		</thead>
		<?php $i = 1; ?>
		<?php $total = ''; ?>
		<?php foreach($this->customerList as $customer) : ?>
			<tr>
				<td><?php echo $i; ?></td>
				<td><?php echo $customer['contactid']; ?></td>
				<td><?php echo $customer['name1']; ?></td>
				<td><?php echo $customer['subtotal']; ?></td>
				<td><?php echo $customer['quantity']; ?></td>
				<td><?php echo $customer['share']; ?>%</td>
				<td></td>
			</tr>
			<?php $total = $customer['total']; ?>
			<?php ++$i; ?>
		<?php endforeach; ?>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td><b><?php echo $total; ?></b></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>
<?php else : ?>
	<p><?php echo $this->translate('STATISTICS_NO_DATA'); ?></p>
<?php endif; ?>
