<?php         
$this->title = $this->translate('SETTINGS');
$this->headTitle($this->title);
echo $this->MenuSettings();
?>

<table id="settings">
	<thead>
		<tr>
			<th>
				<?php echo $this->translate("SETTINGS_COUNTRY_CODE"); ?>
			</th>
			<th>
				<?php echo $this->translate("SETTINGS_COUNTRY"); ?>
			</th>
			<th>ID</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->countries as $country) { ?>
		<tr id="line<?php echo $country['id']; ?>">
			<td id="code">
				<div><?php echo $country['code']; ?></div>
				<?php echo $this->forms[$country['id']]->getElement('code'); ?>
			</td>
			<td id="name">
				<div><?php echo $country['name']; ?></div>
				<?php echo $this->forms[$country['id']]->getElement('name'); ?>
			</td>
			<td id="id">
				<div><?php echo $country['id']; ?></div>
				<?php echo $this->forms[$country['id']]->getElement('id'); ?>
			</td>
			<td>
				<?php echo $this->Button("edit"); ?>
				<?php echo $this->Button("save", "saveSetting(".$country['id'].")", null, null, "display:none"); ?>
				<?php echo $this->Button("delete", "deleteSetting(".$country['id'].", deleteConfirm)"); ?>
				<?php echo $this->Button("cancel", null, null, null, "display:none"); ?>
			</td>
		</tr>
		<?php } ?>
		<tr id="line0" style="display:none;">
			<td id="code">
				<div></div>
				<?php echo $this->form->getElement('code'); ?>
			</td>
			<td id="name">
				<div></div>
				<?php echo $this->form->getElement('name'); ?>
			</td>
			<td id="id">
				<div></div>
				<?php echo $this->form->getElement('id'); ?>
			</td>
			<td>
				<?php echo $this->Button("save", "saveSetting(0)", null, null, "display:none"); ?>
			</td>
		</tr>
	</tbody>
</table>
