<?php		 
$this->title = $this->translate('SALES_ORDERS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="salesorderid" width="5%">
				<?php echo $this->translate('SALES_ORDERS_SALES_ORDER_ID'); ?>
			</th>
			<th class="title" width="28%">
				<?php echo $this->translate('SALES_ORDERS_TITLE'); ?>
			</th>
			<th class="contactid" width="5%">
				<?php echo $this->translate('SALES_ORDERS_CONTACT'); ?>
			</th>
			<th class="billingaddress" width="20%">
				<?php echo $this->translate('SALES_ORDERS_BILLING_ADDRESS'); ?>
			</th>
			<th class="notes" width="15%">
				<?php echo $this->translate('SALES_ORDERS_NOTES') ?>
			</th>
			<th class="salesorderdate" width="8%">
				<?php echo $this->translate('SALES_ORDERS_SALES_ORDER_DATE'); ?>
			</th>
			<th class="total" width="8%">
				<?php echo $this->translate('SALES_ORDERS_TOTAL'); ?>
			</th>
			<th class="state" width="6%">
				<?php echo $this->translate('SALES_ORDERS_STATE'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->salesorders as $salesorder) : ?>
		<tr class="state<?php echo $salesorder->state; ?><?php echo $salesorder->pinned ? ' pinned' : ''; ?>">
			<td><input class="id" type="checkbox" value="<?php echo $salesorder->id ?>" name="id"/></td>
			<td class="salesorderid">
				<?php if($salesorder->salesorderid) : ?>
					<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'salesorder', 'action'=>'edit', 'id'=>$salesorder->id)); ?>">
						<?php echo $this->escape($salesorder->salesorderid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_TITLE') ?>" class="title">
				<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'salesorder', 'action'=>'edit', 'id'=>$salesorder->id)); ?>">
					<?php echo $salesorder->title ? $this->escape($salesorder->title) : $this->escape($salesorder->id); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_CONTACT') ?>" class="contactid">
				<?php if($salesorder->contactid) : ?>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$salesorder->cid)); ?>">
						<?php echo $this->escape($salesorder->contactid); ?><br/>
						<?php echo $this->escape($salesorder->billingname1); ?>
						<?php if($salesorder->billingname2) echo "<br/>".$this->escape($salesorder->billingname2); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_BILLING_ADDRESS') ?>" class="billingaddress">
				<?php echo $this->escape($salesorder->billingstreet); ?><br/>
				<?php echo $this->escape($salesorder->billingpostcode); ?><br/>
				<?php echo $this->escape($salesorder->billingcity); ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_NOTES') ?>" class="notes">
				<?php if($salesorder->notes) : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $salesorder->notes; ?>" data-type="textarea"><?php echo $salesorder->notes; ?></pre>
				<?php else : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $salesorder->notes; ?>" data-type="textarea" data-empty="true"><?php echo $this->translate('TOOLBAR_NEW') ;?></pre>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_SALES_ORDER_DATE') ?>" class="salesorderdate">
				<?php if($salesorder->salesorderdate) echo $this->escape(date("d.m.Y", strtotime($salesorder->salesorderdate))); ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_TOTAL') ?>" class="total">
				<?php echo $this->escape($salesorder->total); ?>
			</td>
			<td data-label="<?php echo $this->translate('SALES_ORDERS_STATE') ?>" class="state">
				<?php if($salesorder->state == '105' || $salesorder->state == '106') : ?>
					<?php echo $this->translate($this->escape($this->options['states'][$salesorder->state])); ?>
				<?php else : ?>
					<span class="editable" data-name="state" data-value="<?php echo $salesorder->state; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['states'][$salesorder->state])); ?></span>
				<?php endif; ?>
			</td>
			<td class="pin">
				<?php if($salesorder->pinned) : ?>
					<input type = "button" onclick = "pin(<?php echo $salesorder->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
				<?php else : ?>
					<input type = "button" onclick = "pin(<?php echo $salesorder->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
				<?php endif; ?>
			</td>
			<td class="buttons">
				<?php if($salesorder->state == '105' || $salesorder->state == '106') : ?>
					<?php echo $this->toolbar->viewInline; ?>
				<?php else : ?>
					<?php echo $this->toolbar->editInline; ?>
				<?php endif; ?>
				<?php echo $this->toolbar->copyInline; ?>
				<?php echo $this->toolbar->pdfInline; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td></td>
			<td class="toolbar">
				<?php echo $this->ToolbarBottom(); ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="total">
				<?php echo $this->salesorders->total; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
