<?php
$this->title = $this->form->getValue('name1');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->Messages();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'contact',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'contactperson' => ['title' => 'TABS_CONTACT_PERSONS'],
		'payment' => ['title' => 'TABS_PAYMENT'],
		'history' => ['title' => 'TABS_HISTORY', 'html' => $this->History()],
		'messages' => ['title' => 'TABS_MESSAGES', 'html' => $this->EmailMessages(), 'a_attrs' => ['onclick'=>"getEmailmessages()"]],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files(), 'show' => (bool)$this->dirwritable],
		'downloads' => ['title' => 'TABS_DOWNLOADS', 'html' => $this->Downloads()],
	]
]); ?>


		<form id="contact" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-6">
					<dl class="form">
						<div id="tag" class="multiformContainer" data-parentid="<?php echo $this->form->getValue('id'); ?>" data-controller="tag">
							<?php echo $this->MultiForm('contacts', 'tag', $this->tags, 'tag', 'TAGS'); ?>
						</div>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-6">
					<dl class="form">
						<h4><?php echo $this->translate('COMMENTS'); ?></h4>
						<div id="comment" class="multiformContainer" data-parentid="<?php echo $this->form->getValue('id'); ?>" data-controller="comment">
							<?php echo $this->MultiForm('default', 'comment', $this->comments); ?>
						</div>
					</dl>
				</div>
			</div>
		</form>
