<?php
$this->title = $this->translate('CONTACTS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<div style="text-align: right;"><?php echo count($this->contacts); ?></div>
<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id" width="5%">
				<?php echo $this->translate('CONTACTS_CONTACT_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('CONTACTS_NAME'); ?>
			</th>
			<th class="phone" width="12%">
				<?php echo $this->translate('CONTACTS_PHONE'); ?>
			</th>
			<th class="street" width="12%">
				<?php echo $this->translate('CONTACTS_STREET'); ?>
			</th>
			<th class="postcode" width="7%">
				<?php echo $this->translate('CONTACTS_POSTCODE'); ?>
			</th>
			<th class="city" width="10%">
				<?php echo $this->translate('CONTACTS_CITY'); ?>
			</th>
			<th class="country" width="10%">
				<?php echo $this->translate('CONTACTS_COUNTRY'); ?>
			</th>
			<th class="notes" width="15%">
				<?php echo $this->translate('CONTACTS_NOTES') ?>
			</th>
			<th class="category" width="12%">
				<?php echo $this->translate('CONTACTS_CATEGORY'); ?>
			</th>
			<th class="tags" width="12%">
				<?php echo $this->translate('TAGS'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->contacts as $contact) : ?>
			<?php echo $contact->pinned ? '<tr class="pinned">' : '<tr>'; ?>
				<td><input class="id" type="checkbox" value="<?php echo $contact->id ?>" name="id"/></td>
				<td data-label="<?php echo $this->translate('CONTACTS_CONTACT_ID') ?>" class="id">
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$contact->id)); ?>">
						<?php echo $this->escape($contact->contactid); ?>
					</a>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_NAME') ?>" class="name">
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$contact->id)); ?>">
						<?php echo $this->escape($contact->name1); ?>
						<?php if($contact->name2) echo "<br/>".$this->escape($contact->name2); ?>
					</a>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_PHONE') ?>" class="phone">
					<?php echo str_replace(',', '<br>', $this->escape($contact->phones)); ?>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_STREET') ?>" class="street">
					<?php echo $this->escape($contact->street); ?>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_POSTCODE') ?>" class="postcode">
					<?php echo $this->escape($contact->postcode); ?>
				</td>
				<td  data-label="<?php echo $this->translate('CONTACTS_CITY') ?>" class="city">
					<?php echo $this->escape($contact->city); ?>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_COUNTRY') ?>" class="country">
					<?php if($contact->country) echo $this->escape($this->translate($contact->country)); ?>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_NOTES') ?>" class="notes">
					<?php if($contact->notes) : ?>
						<pre class="editable" data-name="notes" data-value="<?php echo $creditnote->notes; ?>" data-type="textarea"><?php echo $contact->notes; ?></pre>
					<?php else : ?>
						<pre class="editable" data-name="notes" data-value="<?php echo $creditnote->notes; ?>" data-type="textarea" data-empty="true"><?php echo $this->translate('TOOLBAR_NEW') ;?></pre>
					<?php endif; ?>
				</td>
				<td data-label="<?php echo $this->translate('CONTACTS_CATEGORY') ?>" class="category">
					<?php if($contact->catid && isset($this->options['categories'][$contact->catid])) : ?>
						<span class="editable" data-name="catid" data-value="<?php echo $contact->catid; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['categories'][$contact->catid]['title'])); ?></span>
					<?php else : ?>
						<span class="editable" data-name="catid" data-value="" data-type="select"><?php echo $this->translate('TOOLBAR_NEW') ;?></span>
					<?php endif; ?>
				</td>
				<td data-label="<?php echo $this->translate('TAGS') ?>" class="tags">
					<?php foreach($this->tagEntites[$contact->id] as $tagEntity) : ?>
						<span><?php echo $this->escape($tagEntity['tag']); ?></span>
					<?php endforeach; ?>
					<span class="editable" data-name="tagid" data-value="" data-type="select"></span>
				</td>
				<td class="pin">
					<?php if($contact->pinned) : ?>
						<input type = "button" onclick = "pin(<?php echo $contact->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
					<?php else : ?>
						<input type = "button" onclick = "pin(<?php echo $contact->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
					<?php endif; ?>
				</td>
				<td class="buttons">
					<?php echo $this->toolbar->editInline; ?>
					<?php echo $this->toolbar->copyInline; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td>
				<div class="toolbar bottom">
					<?php echo $this->ToolbarBottom(); ?>
				</div>
			</td>
			<td></td>
		</tr>
	</tbody>
</table>
