<?php		 
$this->title = $this->translate('CONTACTS');
$this->headTitle($this->title);
?>

<table id="data">
	<thead>
		<tr>
			<th><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id"><?php echo $this->translate('CONTACTS_CONTACT_ID') ?></th>
			<th class="name"><?php echo $this->translate('CONTACTS_NAME') ?></th>
			<th class="phone"><?php echo $this->translate('CONTACTS_PHONE') ?></th>
			<th class="street"><?php echo $this->translate('CONTACTS_STREET') ?></th>
			<th class="postcode"><?php echo $this->translate('CONTACTS_POSTCODE') ?></th>
			<th class="city"><?php echo $this->translate('CONTACTS_CITY') ?></th>
			<th class="country"><?php echo $this->translate('CONTACTS_COUNTRY') ?></th>
			<th class="category"><?php echo $this->translate('ITEMS_CATEGORY'); ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->contacts as $contact) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $contact->id ?>" name="id"/></span></td>
				<td class="id">
					<?php echo $this->escape($contact->contactid);?>
				</td>
				<td class="name">
					<?php echo $this->escape($contact->name1);?>
					<?php if($contact->name2) echo "<br/>".$this->escape($contact->name2);?>
				</td>
				<td class="phone">
					<?php //echo $this->escape($contact->phone1);?>
				</td>
				<td class="street">
					<?php echo $this->escape($contact->street);?>
				</td>
				<td class="postcode">
					<?php echo $this->escape($contact->postcode);?>
				</td>
				<td class="city">
					<?php echo $this->escape($contact->city);?>
				</td>
				<td class="country">
					<?php echo $this->escape($contact->country);?>
				</td>
				<td class="category">
					<?php if($contact->catid) echo $this->escape($this->categories[$contact->catid]['title']); ?>
				</td>
				<td class="buttons">
					<?php echo $this->Button('apply', 'window.parent.applyContact('.$this->escape($contact->id).')'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
