<?php 
$this->title = $this->translate('UPLOAD');
$this->headTitle($this->title);
?>
<script type="text/javascript">
$(document).ready(function(){
	$.ajax({
		type: "POST",
		url: baseUrl+"/"+controller+"/files/id/"+id,
		cache: false,
		success: function(data){
			$('#files', parent.document).html(data);
		}
	});
});
</script>
<form id="upload" enctype="multipart/form-data" action="" method="post">
	<dl class="form">
		<?php echo $this->form->getElement('file') ?>
		<?php echo $this->form->getElement('submit') ?>
	</dl>
</form>
