<?php $s = 1; ?>
<?php $sets = count($this->sets); ?>
<?php if($sets == 0) : ?>
	<input type="hidden" class="setid" name="setid" value="0">
	<div class="toolbar positionsets" style="float:right;">
		<?php echo $this->toolbarPositions->addset; ?>
	</div>
<?php endif; ?>
<?php foreach($this->sets as $setid => $set) : ?>
	<div class="set">
		<input type="hidden" class="setid" name="setid" value="<?php echo $setid; ?>">
		<?php echo $this->ToolbarPositionSets($sets, $s); ?>
		<h3><span class="editable" data-name="title" data-value="<?php echo $set['title']; ?>" data-type="input" data-id="<?php echo $setid; ?>" data-controller="positionset"><?php echo $set['title']; ?></span></h3>
		<?php echo $this->ToolbarPositions(); ?>
		<?php if(isset($this->forms[$setid]) && ($length = count($this->forms[$setid]))) : ?>
		<table id="positions">
			<thead>
				<tr>
					<th><input type="checkbox" class="checkall" name="checkall"/></th>
					<th><?php echo $this->translate('POSITION'); ?></th>
					<th class="flex50"><?php echo $this->translate('POSITIONS_ITEM'); ?></th>
					<th><?php echo $this->translate('POSITIONS_TOTAL'); ?></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php foreach($this->forms[$setid] as $position) : ?>
					<tr class="position<?php echo $position['form']->getValue('id'); ?> wrap master">
						<td class="id">
							<input class="id" type="checkbox" value="<?php echo $position['form']->getValue('id'); ?>" name="id"/>
						</td>
						<td class="position">
							<span><?php echo $position['form']->getValue('ordering'); ?></span>
							<?php echo $position['form']->ordering; ?>
						</td>
						<td class="flex50">
							<table>
								<tr>
									<td class="sku">
										<?php echo $position['form']->sku; ?>
									</td>
									<td class="title">
										<?php echo $position['form']->title; ?>
									</td>
								</tr>
								<tr>
									<td class="description">
										<input class="id" type="hidden" value="<?php echo $position['form']->getValue('id'); ?>" name="id"/>
										<?php echo $position['form']->description; ?>
									</td>
								</tr>
								<tr>
									<td class="image">
										<input class="id" type="hidden" value="<?php echo $position['form']->getValue('id'); ?>" name="id"/>
										<?php echo $position['form']->image; ?>
									</td>
								</tr>
							</table>
						</td>
						<td>
							<table>
								<tr>
									<td class="price">
										<?php echo $position['form']->price; ?>
									</td>
								</tr>
								<tr>
									<td class="taxrate">
										<?php echo $position['form']->taxrate; ?>
									</td>
								</tr>
							</table>
						</td>
						<td>
							<table>
								<tr>
									<td class="priceruleamount">
										<?php echo $position['form']->priceruleamount; ?>
									</td>
								</tr>
								<tr>
									<td class="priceruleaction">
										<?php echo $position['form']->priceruleaction; ?>
									</td>
								</tr>
							</table>
						</td>
						<td>
							<table>
								<tr>
									<td class="quantity">
										<?php echo $position['form']->quantity; ?>
									</td>
								</tr>
								<tr>
									<td class="uom">
										<?php echo $position['form']->uom; ?>
									</td>
								</tr>
							</table>
						</td>
						<td class="total">
							<?php echo $position['form']->getValue('total'); ?>
						</td>
						<?php //Display buttons if parent not completed ?>
						<?php if($this->parent['state'] != '105' || $this->parent['state'] != '106') : ?>
						<td class="buttons">
							<?php echo $this->toolbar->deletepos; ?>
							<?php echo $this->toolbar->copypos; ?>
							<?php if($i>1) : ?>
								<?php echo $this->toolbar->sortup; ?>
							<?php endif; ?>
							<?php if($i<$length) : ?>
								<?php echo $this->toolbar->sortdown; ?>
							<?php endif; ?>
						</td>
						<?php endif; ?>
					</tr>
					<?php $c = 1; ?>
					<?php if(isset($this->childs[$position['form']->getValue('id')])) : ?>
					<?php $childs = $this->childs[$position['form']->getValue('id')]; ?>
					<?php if(isset($childs) && ($childsCount = count($childs))) : ?>
						<?php foreach($childs as $child) : ?>
							<tr class="position<?php echo $child->getValue('id'); ?> wrap child" data-masterid="<?php echo $position['form']->getValue('id'); ?>">
								<td style="max-width: 75px;"><input class="id" type="checkbox" value="<?php echo $child->getValue('id'); ?>" name="id"/></td>
								<td><?php echo $child->sku; ?></td>
								<td><?php echo $child->title; ?></td>
								<td><?php echo $child->description; ?></td>
								<td style="max-width: 200px;"><?php echo $child->price; ?></td>
								<?php if($this->parent['state'] != '105' || $this->parent['state'] != '106') : ?>
								<td class="buttons">
									<?php echo $this->toolbar->deletepos; ?>
									<?php echo $this->toolbar->copypos; ?>
									<?php if($c>1) : ?>
										<?php echo $this->toolbar->sortup; ?>
									<?php endif; ?>
									<?php if($c<$childsCount) : ?>
										<?php echo $this->toolbar->sortdown; ?>
									<?php endif; ?>
								</td>
								<?php endif; ?>
							</tr>
						<?php ++$c; ?>
						<?php endforeach; ?>
					<?php endif; ?>
					<?php endif; ?>
					<?php if(isset($this->options[$position['form']->getValue('id')]) && count($this->options[$position['form']->getValue('id')])) : ?>
						<tr><td><h4>Optionen</h4></td><td></td><td></td><td></td></tr>
						<?php foreach($this->options[$position['form']->getValue('id')] as $option) : ?>
							<tr>
								<td><input class="id" type="checkbox" value="<?php echo $option->id; ?>" name="id"/></td>
								<td><?php echo $option->sku; ?></td>
								<td><?php echo $option->title; ?></td>
								<td><?php echo $option->description; ?></td>
								<td><?php echo $option->price; ?></td>
								<td class="buttons">
									<?php //echo $this->controller; ?>
									<?php echo $this->Button('add', 'addOption(\''.$this->parent['type'].'\', \'pos\', '.$this->escape($option->id).', '.$this->escape($setid).', '.$position['form']->getValue('id').')'); ?>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php endif; ?>
					<?php ++$i; ?>
				<?php endforeach; ?>
			</tbody>
		</table>

		<table id="total">
			<tbody>
				<tr>
					<td><?php echo $this->translate('POSITIONS_SUBTOTAL'); ?></td>
					<td id="subtotal" align="right"><?php echo $this->parent['subtotal'] ?></td>
				</tr>
				<?php foreach($this->parent['taxes'] as $rate => $tax) : ?>
					<tr>
						<td><?php echo $this->translate('POSITIONS_TAXES')." (".$tax['title'].")"; ?></td>
						<td id="taxes" align="right" data-rate="<?php echo $rate; ?>"><?php echo $tax['value']; ?></td>
					</tr>
				<?php endforeach; ?>
				<tr>
					<td><?php echo $this->translate('POSITIONS_TOTAL'); ?></td>
					<td id="total" align="right"><?php echo $this->parent['total'] ?></td>
				</tr>
			</tbody>
		</table>
		<?php echo $this->ToolbarPositions('bottom'); ?>
		<div style="height:150px"></div>
		<?php endif; ?>
	</div>
	<?php ++$s; ?>
	<hr>
<?php endforeach; ?>
