<?php
$this->title = $this->translate('EBIZ_TRADER_ACCOUNTS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="userid" width="10%">
				<?php echo $this->translate('EBIZ_TRADER_USER_ID'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->accounts as $account) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $account->id ?>" name="id"/></td>
				<td data-label="<?php echo $this->translate('EBIZ_TRADER_USER_ID') ?>" class="userid">
					<span class="editable" data-name="userid"><?php echo $this->escape($account->userid); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy'); ?>
					<?php echo $this->Button('delete'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->userid; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
			</td>
		</tr>
	</tbody>
</table>
