<?php

$this->title = $this->translate('ITEMS_STOCK');
$this->headTitle($this->title);

echo $this->Messages();
echo $this->Pagination();

?>

<div class="dw-list-page">
	<?php echo $this->stocks->render(); ?>
</div>

<?php if(isset($this->stockTotalValue)): ?>
	<div class="dw-stock-summary">
		<strong>
			<?php echo $this->translate(
				'ITEMS_STOCK_TOTAL_VALUE'
			) ?>:
		</strong>

		<?php echo $this->currency(
			$this->stockTotalValue
		) ?>
	</div>
<?php endif; ?>
