<table width="100%">
<thead>
<tr>
	<th id="subject"><?php echo $this->translate('EMAIL_SUBJECT') ?></th>
	<th id="from"><?php echo $this->translate('EMAIL_FROM') ?></th>
	<th id="date"><?php echo $this->translate('EMAIL_DATE') ?></th>
	<th id="attachment"></th>
	<th></th>
</tr>
</thead>
<tbody>
<?php foreach($this->emails as $email) : ?>
<tr<?php if($email["seen"] === false) : ?> class="unread"<?php endif ?>>
	<td id="subject">
		<a href="<?php echo $this->url(array('controller'=>'email', 'action'=>'view', 'id'=>$email['id']));?>">
			<?php echo $this->escape($email["subject"]); ?>
		</a>
	</td>
	<td id="from">
		<a href="<?php echo $this->url(array('controller'=>'email', 'action'=>'view', 'id'=>$email['id']));?>">
			<?php echo $this->escape($email["from"]);?>
		</a>
	</td>
	<td id="date">
		<a href="<?php echo $this->url(array('controller'=>'email', 'action'=>'view', 'id'=>$email['id']));?>">
			<?php echo $this->escape($email["date"]); ?>
		</a>
	</td>
	<td id="attachment">
		<?php if($email["attachment"] === true) : ?>
			<img src="<?php echo $this->baseUrl(); ?>/images/attachment.png">
		<?php endif ?>
	</td>
	<td>
		<a href="<?php echo $this->url(array('controller'=>'email', 'action'=>'reply', 'id'=>$email['id']));?>">
			<?php echo $this->translate('EMAIL_REPLY'); ?>
		</a>
	</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
