<?php		 
$this->title = $this->translate('DELIVERY_ORDERS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="deliveryorderid" width="5%">
				<?php echo $this->translate('DELIVERY_ORDERS_DELIVERY_ORDER_ID'); ?>
			</th>
			<th class="title" width="28%">
				<?php echo $this->translate('DELIVERY_ORDERS_TITLE'); ?>
			</th>
			<th class="contactid" width="5%">
				<?php echo $this->translate('DELIVERY_ORDERS_CONTACT'); ?>
			</th>
			<th class="billingname" width="20%">
			</th>
			<th class="postcode" width="4%">
				<?php echo $this->translate('DELIVERY_ORDERS_POSTCODE'); ?>
			</th>
			<th class="city" width="4%">
				<?php echo $this->translate('DELIVERY_ORDERS_CITY'); ?>
			</th>
			<th class="modified" width="8%">
				<?php echo $this->translate('DELIVERY_ORDERS_MODIFIED'); ?>
			</th>
			<th class="total" width="8%">
				<?php echo $this->translate('DELIVERY_ORDERS_TOTAL'); ?>
			</th>
			<th class="state" width="6%">
				<?php echo $this->translate('DELIVERY_ORDERS_STATE'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->deliveryorders as $deliveryorder) : ?>
		<tr class="state<?php echo $deliveryorder->state; ?><?php echo $deliveryorder->pinned ? ' pinned' : ''; ?>">
			<td><input class="id" type="checkbox" value="<?php echo $deliveryorder->id ?>" name="id"/></td>
			<td class="deliveryorderid">
				<?php if($deliveryorder->deliveryorderid) : ?>
					<a href="<?php echo $this->url(array('controller'=>'deliveryorder', 'action'=>'edit', 'id'=>$deliveryorder->id)); ?>">
						<?php echo $this->escape($deliveryorder->deliveryorderid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_TITLE') ?>" class="title">
				<a href="<?php echo $this->url(array('controller'=>'deliveryorder', 'action'=>'edit', 'id'=>$deliveryorder->id)); ?>">
					<?php echo $deliveryorder->title ? $this->escape($deliveryorder->title) : $this->escape($deliveryorder->id); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_CONTACT') ?>" class="contactid">
				<?php if($deliveryorder->contactid) : ?>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$deliveryorder->cid)); ?>">
						<?php echo $this->escape($deliveryorder->contactid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td class="billingname">
				<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$deliveryorder->cid)); ?>">
					<?php echo $this->escape($deliveryorder->billingname1); ?>
					<?php if($deliveryorder->billingname2) echo "<br/>".$this->escape($deliveryorder->billingname2); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_POSTCODE') ?>" class="billingpostcode">
				<?php echo $this->escape($deliveryorder->billingpostcode); ?> 
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_CITY') ?>" class="billingcity">
				<?php echo $this->escape($deliveryorder->billingcity); ?>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_MODIFIED') ?>" class="modified">
				<?php echo $this->escape(date("d.m.Y", strtotime($deliveryorder->modified))); ?>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_TOTAL') ?>" class="total">
				<?php echo $this->escape($deliveryorder->total); ?>
			</td>
			<td data-label="<?php echo $this->translate('DELIVERY_ORDERS_STATE') ?>" class="state">
				<?php if($deliveryorder->state == '105' || $deliveryorder->state == '106') : ?>
					<?php echo $this->translate($this->escape($this->options['states'][$deliveryorder->state])); ?>
				<?php else : ?>
					<span class="editable" data-name="state" data-value="<?php echo $deliveryorder->state; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['states'][$deliveryorder->state])); ?></span>
				<?php endif; ?>
			</td>
			<td class="pin">
				<?php if($deliveryorder->pinned) : ?>
					<input type = "button" onclick = "pin(<?php echo $deliveryorder->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
				<?php else : ?>
					<input type = "button" onclick = "pin(<?php echo $deliveryorder->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
				<?php endif; ?>
			</td>
			<td class="buttons">
				<?php if($deliveryorder->state == '105' || $deliveryorder->state == '106') : ?>
					<?php echo $this->toolbar->viewInline; ?>
				<?php else : ?>
					<?php echo $this->toolbar->editInline; ?>
				<?php endif; ?>
				<?php echo $this->toolbar->copyInline; ?>
				<?php echo $this->toolbar->pdfInline; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td></td>
			<td class="toolbar">
				<?php echo $this->ToolbarBottom(); ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="total">
				<?php echo $this->deliveryorders->total; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
