<?php 
$this->title = $this->deliveryorder['title'] ? $this->deliveryorder['title'] : $this->translate('DELIVERY_ORDER')." ".$this->deliveryorder['deliveryorderid'];
$this->headTitle($this->title);
echo $this->FileManager();
?>

<ul class="tabs">
	<li class="active"><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
	<li><a href="#tabFiles"><?php echo $this->translate('TABS_FILES') ?></a></li>
	<li><a href="#tabDocument" onclick="savePdf()"><?php echo $this->translate('TABS_DOCUMENT') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content active">
		<div id="left">
			<dl class="view">
				<dt><label><?php echo $this->translate('DELIVERY_ORDERS_DELIVERY_ORDER_ID') ?></label></dt>
				<dd><?php echo $this->deliveryorder['deliveryorderid']; ?></dd>
				<?php if($this->deliveryorder['vatin']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_VATIN') ?></label></dt>
					<dd><?php echo $this->deliveryorder['vatin']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['deliveryorderdate']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_DELIVERY_ORDER_DATE') ?></label></dt>
					<dd><?php echo $this->deliveryorder['deliveryorderdate']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['orderdate'] && ($this->deliveryorder['orderdate'] != "0000-00-00")) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_ORDER_DATE') ?></label></dt>
					<dd><?php echo $this->deliveryorder['orderdate']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['deliverydate'] && ($this->deliveryorder['deliverydate'] != "0000-00-00")) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_DELIVERY_DATE') ?></label></dt>
					<dd><?php echo $this->deliveryorder['deliverydate']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['paymentmethod']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_PAYMENT_METHOD') ?></label></dt>
					<dd><?php echo $this->deliveryorder['paymentmethod']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['shippingmethod']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_SHIPPING_METHOD') ?></label></dt>
					<dd><?php echo $this->deliveryorder['shippingmethod']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['header']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_HEADER') ?></label></dt>
					<dd><?php echo $this->deliveryorder['header']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['footer']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_FOOTER') ?></label></dt>
					<dd><?php echo $this->deliveryorder['footer']; ?></dd>
				<?php } ?>
				<?php if($this->deliveryorder['info']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_INFO') ?></label></dt>
					<dd><?php echo $this->deliveryorder['info']; ?></dd>
				<?php } ?>
			</dl>
		</div>
		<div id="right">
			<dl class="view">
				<dt><label><?php echo $this->translate('DELIVERY_ORDERS_CONTACT_ID') ?></label></dt>
				<dd>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$this->deliveryorder['contactid']));?>"><?php echo $this->deliveryorder['contactid']; ?></a>
					<input id="contactid" type="hidden" value="<?php echo $this->deliveryorder['contactid']; ?>" size="5" readonly="readonly" name="contactid"/>
				</dd>
				<dt><label><?php echo $this->translate('DELIVERY_ORDERS_BILLING_ADDRESS') ?></label></dt>
				<dd>
					<?php echo $this->deliveryorder['billingname1']; ?>
					<?php if($this->deliveryorder['billingname2']) echo "</br>".$this->deliveryorder['billingname2']; ?>
					<?php if($this->deliveryorder['billingdepartment']) echo "</br>".$this->deliveryorder['billingdepartment']; ?>
					<?php if($this->deliveryorder['billingstreet']) echo "</br>".$this->deliveryorder['billingstreet']; ?>
					<?php if($this->deliveryorder['billingpostcode'] || $this->deliveryorder['billingcity']) { ?>
						</br>
						<?php if($this->deliveryorder['billingpostcode']) echo $this->deliveryorder['billingpostcode']; ?>
						<?php if($this->deliveryorder['billingcity']) echo $this->deliveryorder['billingcity']; ?>
					<?php } ?>
					<?php if($this->deliveryorder['billingcountry']) echo "</br>".$this->translate($this->deliveryorder['billingcountry']); ?>
				</dd>
				<?php if($this->deliveryorder['shippingname1'] || $this->deliveryorder['shippingname2']) { ?>
					<dt><label><?php echo $this->translate('DELIVERY_ORDERS_SHIPPING_ADDRESS') ?></label></dt>
					<dd>
						<?php echo $this->deliveryorder['shippingname1']; ?>
						<?php if($this->deliveryorder['shippingname2']) echo "</br>".$this->deliveryorder['shippingname2']; ?>
						<?php if($this->deliveryorder['shippingdepartment']) echo "</br>".$this->deliveryorder['shippingdepartment']; ?>
						<?php if($this->deliveryorder['shippingstreet']) echo "</br>".$this->deliveryorder['shippingstreet']; ?>
						<?php if($this->deliveryorder['shippingpostcode'] || $this->deliveryorder['shippingcity']) { ?>
							</br>
							<?php if($this->deliveryorder['shippingpostcode']) echo $this->deliveryorder['shippingpostcode']; ?>
							<?php if($this->deliveryorder['shippingcity']) echo $this->deliveryorder['shippingcity']; ?>
						<?php } ?>
						<?php if($this->deliveryorder['shippingcountry']) echo "</br>".$this->translate($this->deliveryorder['shippingcountry']); ?>
						<?php if($this->deliveryorder['shippingphone']) echo "</br>".$this->deliveryorder['shippingphone']; ?>
					</dd>
				<?php } ?>
			</dl>
		</div>
		<div style="clear:left"></div>
		<h3><?php echo $this->translate('DELIVERY_ORDERS_POSITIONS') ?></h3>
		<div id="positions">
			<?php
				$i = 1;
				$length = count($this->positions);
			?>
			<table id="positions">
			<thead>
			<tr>
			<th id="id">ID</th>
			<th style="width:8%"><?php echo $this->translate('POSITIONS_SKU'); ?></th>
			<th style="width:22%"><?php echo $this->translate('POSITIONS_TITLE'); ?></th>
			<th style="width:55%"><?php echo $this->translate('POSITIONS_DESCRIPTION'); ?></th>
			<th style="width:8%"><?php echo $this->translate('POSITIONS_PRICE'); ?></th>
			<th style="width:2%"><?php echo $this->translate('POSITIONS_QUANTITY'); ?></th>
			<th style="width:2%"><?php echo $this->translate('POSITIONS_UOM'); ?></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($this->positions as $position) { ?>
				<tr id="position<?php echo $position['id']; ?>">
				<td id="id"><span><?php echo $position['id']; ?></span></td>
				<td id="sku"><span><?php echo $position['sku']; ?></span></td>
				<td id="title"><span><?php echo $position['title']; ?></span></td>
				<td id="description"><span><?php echo str_replace("\n", "<br>", $position['description']); ?></span></td>
				<td id="price"><span><?php echo $position['price']; ?></span></td>
				<td id="quantity"><span><?php echo $position['quantity']; ?></span></td>
				<td id="uom"><span><?php echo $position['uom']; ?></span></td>
				</tr>
				<?php ++$i; ?>
			<?php } ?>
			</tbody>
			</table>

			<table id="total" align="right">
				<tbody>
					<tr>
						<td><?php echo $this->translate('POSITIONS_SUBTOTAL'); ?></td>
						<td align="right"><?php echo $this->deliveryorder['subtotal']; ?></td>
					</tr>
					<tr>
						<td><?php echo $this->translate('POSITIONS_TAXES'); ?></td>
						<td align="right"><?php echo $this->deliveryorder['taxes']; ?></td>
					</tr>
					<tr>
						<td><?php echo $this->translate('POSITIONS_TOTAL'); ?></td>
						<td align="right"><?php echo $this->deliveryorder['total']; ?></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div style="clear:left"></div>
	</div>
	<div id="tabFiles" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
		<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?lang=de&type=0" width="100%" height="700px"></iframe>
	</div>
	<div id="tabDocument" class="tab_content">
		<p>
			<a href="<?php echo $this->url(array('controller'=>'deliveryorder', 'action'=>'download', 'id'=>$this->deliveryorder['id']));?>" target="_blank"><?php echo $this->translate('DELIVERY_ORDERS_DOWNLOAD_PDF') ?></a>
		</p>
		<div id="output"></div>
	</div>
</div>
