<?php 
$this->title = $this->translate('ITEMS_NEW_INVENTORY');
$this->headTitle($this->title);
?>

<ul class="tabs">
	<li><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content">
		<form id="inventory" name="inventory" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-7">
					<dl class="form">
						<?php echo $this->form->getElement('id') ?>
						<?php echo $this->form->getElement('sku') ?>
						<?php echo $this->form->getElement('title') ?>
						<?php echo $this->form->getElement('type') ?>
						<?php echo $this->form->getElement('barcode') ?>
						<?php echo $this->form->getElement('quantity') ?>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-5">
				</div>
			</div>
		</form>
	</div>
</div>
