<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id" width="5%">
				<?php echo $this->translate('ADMIN_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('ADMIN_NAME'); ?>
			</th>
			<th class="logo" width="20%">
				<?php echo $this->translate('ADMIN_LOGO'); ?>
			</th>
			<th class="website" width="20%">
				<?php echo $this->translate('ADMIN_WEBSITE'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->templates as $template) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $template->id ?>" name="id"/></td>
				<td class="id">
					<?php echo $this->escape($template->id); ?>
				</td>
				<td class="name">
					<span class="editable" data-name="description"><?php echo $this->escape($template->description); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="logo"><?php echo $this->escape($template->logo); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="website"><?php echo $this->escape($template->website); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy', '', $this->translate('TOOLBAR_COPY')); ?>
					<?php echo $this->Button('delete', '', $this->translate('TOOLBAR_DELETE')); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
			</td>
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->description; ?>
			</td>
			<td>
				<?php echo $this->form->logo; ?>
			</td>
			<td>
				<?php echo $this->form->website; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
				<?php //echo $this->toolbar->cancel; ?>
			</td>
		</tr>
	</tbody>
</table>
