<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('PROCESSES_NEW_PROCESS');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<ul class="tabs">
	<li<?php if($this->activeTab == "#tabOverview") : ?> class="active"<?php endif; ?>>
		<a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW'); ?></a></li>
	<li<?php if($this->activeTab == "#tabPositions") : ?> class="active"<?php endif; ?>>
		<a href="#tabPositions" onclick="getPositions()"><?php echo $this->translate('TABS_POSITIONS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabCustomer") : ?> class="active"<?php endif; ?>>
		<a href="#tabCustomer"><?php echo $this->translate('TABS_CUSTOMER'); ?></a></li>
	<li<?php if($this->activeTab == "#tabSupplier") : ?> class="active"<?php endif; ?>>
		<a href="#tabSupplier"><?php echo $this->translate('TABS_SUPPLIER'); ?></a></li>
	<li<?php if($this->activeTab == "#tabShippingAddress") : ?> class="active"<?php endif; ?>>
		<a href="#tabShippingAddress"><?php echo $this->translate('TABS_SHIPPING_ADDRESS'); ?></a></li>
	<li<?php if($this->activeTab == "#tabFiles") : ?> class="active"<?php endif; ?>>
		<a href="#tabFiles"><?php echo $this->translate('TABS_FILES'); ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content<?php if($this->activeTab == '#tabOverview' || !$this->activeTab) : ?> active<?php endif; ?>">
		<form id="process" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="row">
                <div class="col-sm-12 col-lg-7">
				    <dl class="form">
						<?php echo $this->form->getElement('id'); ?>
						<?php echo $this->form->getElement('title'); ?>
						<h4><?php echo $this->translate('PROCESSES_CUSTOMER'); ?></h4>
						<?php echo $this->toolbar->select; ?>
						<div style="clear:left"></div>
						<?php echo $this->form->getElement('customerid'); ?>
						<?php echo $this->form->getElement('billingname1'); ?>
						<?php echo $this->form->getElement('notes'); ?>
				    </dl>
		        </div>
                <div class="col-sm-12 col-lg-5">
				    <dl class="form">
						<?php echo $this->form->getElement('info'); ?>
	                </dl>
	            </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-lg-4">
                    <dl class="form">
						<h4><?php echo $this->translate('PROCESSES_PAYMENT'); ?></h4>
						<?php echo $this->form->getElement('total'); ?>
						<?php echo $this->form->getElement('paymentmethod'); ?>
						<?php echo $this->form->getElement('paymentdate'); ?>
						<?php echo $this->form->getElement('invoiceid'); ?>
						<?php echo $this->form->getElement('invoicedate'); ?>
						<?php echo $this->form->getElement('paymentstatus'); ?>
                    </dl>
	            </div>
                <div class="col-sm-12 col-lg-4">
                    <dl class="form">
						<h4><?php echo $this->translate('PROCESSES_PREPAYMENT'); ?></h4>
						<?php echo $this->form->getElement('prepaymenttotal'); ?>
						<?php echo $this->form->getElement('prepaymentdate'); ?>
						<?php echo $this->form->getElement('prepaymentinvoiceid'); ?>
						<?php echo $this->form->getElement('prepaymentinvoicedate'); ?>
                    </dl>
	            </div>
                <div class="col-sm-12 col-lg-4">
                    <dl class="form">
						<h4><?php echo $this->translate('PROCESSES_CREDIT_NOTE'); ?></h4>
						<?php echo $this->form->getElement('creditnotetotal'); ?>
						<?php echo $this->form->getElement('creditnoteid'); ?>
						<?php echo $this->form->getElement('creditnotedate'); ?>
                    </dl>
	            </div>
            </div>
        </form>
	</div>
	<div id="tabPositions" class="tab_content<?php if($this->activeTab == '#tabPositions') : ?> active<?php endif; ?>">
		<?php echo $this->ToolbarPositions(); ?>
		<form id="process" enctype="application/x-www-form-urlencoded" action="" method="post">
			<table id="details"<?php if($this->form->getValue('editpositionsseparately')) echo ' class="disabled"'; ?>>
				<tr>
					<td class="deliverystatus <?php echo $this->form->getValue('deliverystatus'); ?>">
						<?php echo $this->form->deliverystatus; ?>
					</td>
					<td>
						<?php echo $this->form->shippingmethod; ?>
					</td>
					<td class="deliverydate">
						<?php echo $this->form->deliverydate; ?>
					</td>
					<td>
						<?php echo $this->form->deliveryorderid; ?>
						<?php //echo $this->form->shipmentdate; ?>
					</td>
					<td>
						<?php echo $this->form->deliveryorderdate; ?>
						<?php //echo $this->form->shipmentnumber; ?>
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<b><?php echo $this->translate('PROCESSES_SUPPLIER_DATA'); ?></b>
					</td>
					<td>
						<?php echo $this->form->supplierid; ?>
					</td>
					<td>
						<?php echo $this->form->purchaseorderid; ?>
					</td>
					<td>
						<?php echo $this->form->suppliersalesorderid; ?>
					</td>
					<td>
						<?php echo $this->form->supplierinvoiceid; ?>
					</td>
					<td>
						<?php echo $this->form->supplierinvoicetotal; ?>
					</td>
				</tr>
				<tr >
					<td class="supplierorderstatus <?php echo $this->form->getValue('supplierorderstatus'); ?>">
						<?php echo $this->form->supplierorderstatus; ?>
					</td>
					<td>
						<?php echo $this->form->suppliername; ?>
					</td>
					<td>
						<?php echo $this->form->purchaseorderdate; ?>
					</td>
					<td>
						<?php echo $this->form->suppliersalesorderdate; ?>
					</td>
					<td>
						<?php echo $this->form->supplierinvoicedate; ?>
					</td>
					<td>
						<?php echo $this->form->supplierpaymentdate; ?>
					</td>
				</tr>
			</table>
			<div class="editpositionsseparately">
				<?php echo $this->form->editpositionsseparately; ?>
			</div>
		</form>
		<div id="positions" <?php if(!$this->form->getValue('editpositionsseparately')) echo ' class="disabled"'; ?>></div>
		<?php echo $this->ToolbarPositions("bottom"); ?>
	</div>
	<div id="tabCustomer" class="tab_content<?php if($this->activeTab == '#tabCustomer') : ?> active<?php endif; ?>">
		<form id="process" enctype="application/x-www-form-urlencoded" action="" method="post">
		    <?php echo $this->toolbar->select; ?>
            <div class="row">
                <div class="col-sm-12 col-lg-7">
				    <dl class="form">
					    <?php echo $this->form->getElement('customerid'); ?>
					    <?php echo $this->form->getElement('billingname1'); ?>
					    <?php echo $this->form->getElement('billingname2'); ?>
					    <?php echo $this->form->getElement('billingdepartment'); ?>
					    <dt><label><b><?php echo $this->translate('CUSTOMERS_ADDRESS'); ?></b></label></dt>
					    <dd></dd>
					    <?php echo $this->form->getElement('billingstreet'); ?>
					    <?php echo $this->form->getElement('billingpostcode'); ?>
					    <?php echo $this->form->getElement('billingcity'); ?>
					    <?php echo $this->form->getElement('billingcountry'); ?>
					    <?php echo $this->form->getElement('vatin'); ?>
					    <?php echo $this->form->getElement('taxfree'); ?>
					    <dt><label><b><?php echo $this->translate('CUSTOMERS_CUSTOMER_DATA'); ?></b></label></dt>
					    <dt id="phone1"<?php if(!$this->customer['phone1']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_PHONE'); ?></label>
					    </dt>
					    <dd id="phone1"<?php if(!$this->customer['phone1']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['phone1']; ?>
					    </dd>
					    <dt id="phone2"<?php if(!$this->customer['phone2']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_PHONE'); ?></label>
					    </dt>
					    <dd id="phone2"<?php if(!$this->customer['phone2']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['phone2']; ?>
					    </dd>
					    <dt id="phone3"<?php if(!$this->customer['phone3']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_PHONE'); ?></label>
					    </dt>
					    <dd id="phone3"<?php if(!$this->customer['phone3']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['phone3']; ?>
					    </dd>
					    <dt id="fax"<?php if(!$this->customer['fax']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_FAX'); ?></label>
					    </dt>
					    <dd id="fax"<?php if(!$this->customer['fax']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['fax']; ?>
					    </dd>
					    <dt id="mobile"<?php if(!$this->customer['mobile']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_MOBILE'); ?></label>
					    </dt>
					    <dd id="mobile"<?php if(!$this->customer['mobile']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['mobile']; ?>
					    </dd>
					    <dt id="email1"<?php if(!$this->customer['email1']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_EMAIL'); ?></label>
					    </dt>
					    <dd id="email1"<?php if(!$this->customer['email1']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['email1']; ?>
					    </dd>
					    <dt id="email2"<?php if(!$this->customer['email2']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_EMAIL'); ?></label>
					    </dt>
					    <dd id="email2"<?php if(!$this->customer['email2']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['email2']; ?>
					    </dd>
					    <dt id="email3"<?php if(!$this->customer['email3']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_EMAIL'); ?></label>
					    </dt>
					    <dd id="email3"<?php if(!$this->customer['email3']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['email3']; ?>
					    </dd>
					    <dt id="internet"<?php if(!$this->customer['internet']) echo ' style="display:none;"'; ?>>
						    <label><?php echo $this->translate('CUSTOMERS_INTERNET'); ?></label>
					    </dt>
					    <dd id="internet"<?php if(!$this->customer['internet']) echo ' style="display:none;"'; ?>>
						    <?php echo $this->customer['internet']; ?>
					    </dd>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-5">
				    <dl class="form">
					    <?php echo $this->form->getElement('customerinfo'); ?>
				    </dl>
			    </div>
			</div>
		</form>
	</div>
	<div id="tabSupplier" class="tab_content<?php if($this->activeTab == '#tabSupplier') : ?> active<?php endif; ?>">
		<form id="process" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="col-sm-12">
				<dl class="form">
					<?php echo $this->form->supplierid; ?>
					<?php echo $this->form->suppliername; ?>
					<?php //echo $this->form->purchaseorderid;?>
					<?php //echo $this->form->purchaseorderdate;?>
					<?php //echo $this->form->suppliersalesorderid;?>
					<?php //echo $this->form->suppliersalesorderdate;?>
					<?php //echo $this->form->supplierinvoiceid;?>
					<?php //echo $this->form->supplierinvoicedate;?>
					<?php //echo $this->form->supplierordered;?>
					<?php //echo $this->form->supplierdeliverydate;?>
				</dl>
			</div>
		</form>
	</div>
	<div id="tabShippingAddress" class="tab_content<?php if($this->activeTab == '#tabShippingAddress') : ?> active<?php endif; ?>">
		<form id="process" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="col-sm-12">
				<dl class="form">
					<?php echo $this->form->getElement('shippingname1'); ?>
					<?php echo $this->form->getElement('shippingname2'); ?>
					<?php echo $this->form->getElement('shippingdepartment'); ?>
					<?php echo $this->form->getElement('shippingstreet'); ?>
					<?php echo $this->form->getElement('shippingpostcode'); ?>
					<?php echo $this->form->getElement('shippingcity'); ?>
					<?php echo $this->form->getElement('shippingcountry'); ?>
					<?php echo $this->form->getElement('shippingemail'); ?>
				</dl>
			</div>
		</form>
	</div>
	<div id="tabFiles" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
		<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?lang=de&type=0" width="100%" height="700px"></iframe>
	</div>
</div>

<div id="popup">
	<div id="addCustomer" class="popup_block">
		<?php if($this->form->getValue('customerid')) : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'contactid'=>$this->form->getValue('customerid'), 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php else : ?>
			<iframe src="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller));?>" width="100%" height="100%"></iframe>
		<?php endif; ?>
	</div>

	<div id="selectPosition" class="popup_block">
		<iframe src="<?php echo $this->url(array('module'=>'items', 'controller'=>'item', 'action'=>'select', 'parent'=>$this->module.'|'.$this->controller.'|'.$this->form->getValue('id')));?>" width="100%" height="100%"></iframe>
	</div>
</div>
