<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('PROCESSES_NEW_PROCESS');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'process',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'billing' => ['title' => 'TABS_BILLING'],
		'supplier' => ['title' => 'TABS_SUPPLIER'],
		'positions' => [
			'title' => 'TABS_POSITIONS',
			'html' => $this->Positions('process'),
			'a_attrs' => [
				'data-tab-load' => 'getPositions',
				'data-parent' => 'process',
				'data-type' => 'pos',
			],
		],
		'customer' => ['title' => 'TABS_CUSTOMER'],
		'shipping' => ['title' => 'TABS_SHIPPING_ADDRESS'],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files()],
		'finish' => ['title' => 'TABS_FINISH'],
	],
]); ?>
<?php echo $this->Popup(); ?>
