<?php
$this->title = $this->translate('ADMIN_UPLOAD');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->FileManager();
?>


<div class="row">
	<div class="col-sm-4 col-lg-2">
		<?php echo $this->AdminMenu(); ?>
	</div>
	<div class="col-sm-8 col-lg-10">
		<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?lang=de&type=0" width="100%" height="700px"></iframe>
	</div>
</div>
