<?php 
$this->title = $this->translate('ITEMS_NEW_ITEM');
$this->headTitle($this->title);
?>

<ul class="tabs">
	<li><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content">
		<form id="item" name="item" enctype="application/x-www-form-urlencoded" action="" method="post">
            <div class="row">
                <div class="col-sm-12 col-lg-7">
				    <dl class="form">
					    <?php echo $this->form->getElement('id') ?>
					    <?php echo $this->form->getElement('sku') ?>
					    <?php echo $this->form->getElement('title') ?>
					    <?php echo $this->form->getElement('type') ?>
					    <?php echo $this->form->getElement('barcode') ?>
					    <?php echo $this->form->getElement('catid') ?>
					    <?php echo $this->form->getElement('manufacturerid') ?>
					    <?php echo $this->form->getElement('manufacturersku') ?>
					    <?php echo $this->form->getElement('quantity') ?>
					    <?php echo $this->form->getElement('uomid') ?>
					    <?php echo $this->form->getElement('cost') ?>
					    <?php echo $this->form->getElement('price') ?>
					    <?php echo $this->form->getElement('margin') ?>
					    <?php echo $this->form->getElement('taxid') ?>
				    </dl>
			    </div>
                <div class="col-sm-12 col-lg-5">
				    <?php echo $this->form->getElement('description') ?>
				    <?php echo $this->form->getElement('info') ?>
			    </div>
		    </div>
		</form>
	</div>
</div>
