<div
	class="dw-positions"
	data-section="attributes"
	data-refresh="positions"
	data-parent="item"
	data-type="atr"
>
	<?php foreach($this->attributes as $attribute): ?>
		<div class="dw-position-card">
			<strong>
				<?php echo $this->escape($attribute->title); ?>
			</strong>

			<?php if($attribute->description !== null && $attribute->description !== ''): ?>
				<span>
					<?php echo $this->escape($attribute->description); ?>
				</span>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>
</div>
