<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->Messages();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'item',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'prices' => ['title' => 'TABS_PRICES'],
		'details' => ['title' => 'TABS_DETAILS'],
		'shop' => ['title' => 'TABS_SHOP', 'show' => (bool)$this->form->getValue('shopid')],
		'ledger' => ['title' => 'TABS_LEDGER', 'html' => $this->Ledger()],
		'attributes' => ['title' => 'TABS_ATTRIBUTES', 'html' => $this->Attributes(), 'a_attrs' => ['onclick'=>"getPositions('item','atr')"]],
		'options' => ['title' => 'TABS_OPTIONS', 'html' => $this->Options(), 'a_attrs' => ['onclick'=>"getPositions('item','opt')"]],
		'images' => ['title' => 'TABS_IMAGES', 'html' => $this->Images()],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files(), 'show' => (bool)$this->dirwritable],
	]
]); ?>
