<?php
$this->title = $this->translate('ITEMS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="sku" width="10%">
				<?php echo $this->translate('ITEMS_SKU'); ?>
			</th>
			<th class="title" width="32%">
				<?php echo $this->translate('ITEMS_TITLE'); ?>
			</th>
			<th class="cost" width="8%">
				<?php echo $this->translate('ITEMS_COST'); ?>
			</th>
			<th class="price" width="8%">
				<?php echo $this->translate('ITEMS_PRICE'); ?>
			</th>
			<th class="quantity" width="8%">
				<?php echo $this->translate('ITEMS_QUANTITY'); ?>
			</th>
			<th width="8%"><?php echo $this->translate('ITEMS_UOM'); ?></th>
			<th width="8%"><?php echo $this->translate('ITEMS_CATEGORY'); ?></th>
			<th width="8%"><?php echo $this->translate('ITEMS_MANUFACTURER'); ?></th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->items as $item) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $item->id ?>" name="id"/></td>
				<td data-label="<?php echo $this->translate('ITEMS_SKU') ?>" class="sku">
					<a href="<?php echo $this->url(array('module'=>'items', 'controller'=>'item', 'action'=>'edit', 'id'=>$item->id)); ?>">
						<?php echo $this->escape($item->sku); ?>
					</a>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_TITLE') ?>" class="title">
					<a href="<?php echo $this->url(array('module'=>'items', 'controller'=>'item', 'action'=>'edit', 'id'=>$item->id)); ?>">
						<?php echo $this->escape($item->title); ?>
					</a><br/>
					<?php echo $this->escape($item->description); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_COST') ?>" class="cost">
					<?php echo $this->escape($item->cost); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_PRICE') ?>" class="price">
					<?php echo $this->escape($item->price); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_QUANTITY') ?>" class="quantity">
					<?php echo $this->escape($item->quantity); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_UOM') ?>" class="uomid">
					<?php if($item->uomid) echo $this->escape($this->uoms[$item->uomid]); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_CATEGORY') ?>" class="category">
					<?php if($item->catid) echo $this->escape($this->options['categories'][$item->catid]['title']); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_MANUFACTURER') ?>" class="manufacturer">
					<?php if($item->manufacturerid) echo $this->escape($this->options['manufacturers'][$item->manufacturerid]); ?>
				</td>
				<td class="buttons">
					<?php echo $this->toolbar->editInline; ?>
					<?php echo $this->toolbar->copyInline; ?>
					<?php echo $this->toolbar->deleteInline; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td colspan="9" rowspan="1">
				<div class="toolbar bottom">
					<?php echo $this->ToolbarBottom(); ?>
				</div>
			</td>
		</tr>
	</tbody>
</table>
