<?php
$this->title = $this->translate('ITEMS');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
echo $this->Pagination();
?>

<table id="data">
	<thead>
		<tr>
			<th><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="sku"><?php echo $this->translate('ITEMS_SKU'); ?></th>
			<th class="title"><?php echo $this->translate('ITEMS_TITLE'); ?></th>
			<th class="cost"><?php echo $this->translate('ITEMS_COST'); ?></th>
			<th class="price"><?php echo $this->translate('ITEMS_PRICE'); ?></th>
			<th class="price"><?php echo $this->translate('ITEMS_CURRENCY'); ?></th>
			<th class="quantity"><?php echo $this->translate('ITEMS_QUANTITY'); ?></th>
			<th class="uomid"><?php echo $this->translate('ITEMS_UOM'); ?></th>
			<th class="manufacturer"><?php echo $this->translate('ITEMS_MANUFACTURER'); ?></th>
			<th class="category"><?php echo $this->translate('ITEMS_CATEGORY'); ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->items as $item) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $item->id ?>" name="id"/></span></td>
				<td class="sku">
					<?php echo $this->escape($item->sku);?>
				</td>
				<td class="title">
					<?php echo $this->escape($item->title);?>
				</td>
				<td class="cost">
					<?php echo $this->escape($item->cost);?>
				</td>
				<td class="price">
					<?php echo $this->escape($item->price);?>
				</td>
				<td class="currency">
					<?php echo $this->escape($item->currency);?>
				</td>
				<td class="quantity">
					<?php if($item->quantity) echo $this->escape($item->quantity);?>
				</td>
				<td class="uomid">
					<?php if($item->uomid && isset($this->options['uoms'][$item->uomid])) echo $this->escape($this->options['uoms'][$item->uomid]); ?>
				</td>
				<td class="manufacturer">
					<?php if($item->manufacturerid && isset($this->options['manufacturers'][$item->manufacturerid])) echo $this->escape($this->options['manufacturers'][$item->manufacturerid]); ?>
				</td>
				<td class="category">
					<?php if($item->catid && isset($this->options['categories'][$item->catid])) echo $this->escape($this->options['categories'][$item->catid]['title']); ?>
				</td>
				<td class="buttons">
					<?php echo $this->Button('apply', 'applyPosition(\''.$this->parent.'\', \'pos\', '.$this->escape($item->id).', window.parent.setid)'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
