<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%">
				<?php if($this->user['admin']) : ?>
					<input type="checkbox" class="checkall" name="checkall"/>
				<?php endif; ?>
			</th>
			<th class="id" width="5%">
				<?php echo $this->translate('ADMIN_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('ADMIN_TEMPLATE_ID'); ?>
			</th>
			<th class="logo" width="20%">
				<?php echo $this->translate('ADMIN_COLUMN'); ?>
			</th>
			<th class="website" width="20%">
				<?php echo $this->translate('ADMIN_TEXT'); ?>
			</th>
			<th class="website" width="20%">
				<?php echo $this->translate('ADMIN_WIDTH'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->footers as $footer) : ?>
			<tr>
				<td>
					<?php if($this->user['admin']) : ?>
						<input class="id" type="checkbox" value="<?php echo $footer->id ?>" name="id"/>
					<?php else : ?>
						<input class="id" type="hidden" value="<?php echo $footer->id ?>" name="id"/>
					<?php endif; ?>
				</td>
				<td class="id">
					<?php echo $this->escape($footer->id); ?>
				</td>
				<td class="name">
					<span class="editable" data-name="templateid"><?php echo $this->escape($footer->templateid); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="column"><?php echo $this->escape($footer->column); ?></span>
				</td>
				<td class="name">
					<pre class="editable" data-name="text" data-type="textarea"><?php echo $this->escape($footer->text); ?></pre>
				</td>
				<td class="name">
					<span class="editable" data-name="width"><?php echo $this->escape($footer->width); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy'); ?>
					<?php echo $this->Button('delete'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
			</td>
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->templateid; ?>
			</td>
			<td>
				<?php echo $this->form->column; ?>
			</td>
			<td>
				<?php echo $this->form->text; ?>
			</td>
			<td>
				<?php echo $this->form->width; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
				<?php //echo $this->toolbar->cancel; ?>
			</td>
		</tr>
	</tbody>
</table>
