<?php 
$this->title = $this->form->getValue('title') ? $this->form->getValue('title') : $this->translate('CREDIT_NOTES_NEW_CREDIT_NOTE');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'creditnote',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'positions' => ['title' => 'TABS_POSITIONS', 'html' => $this->Positions('creditnote'), 'a_attrs' => ['onclick'=>"getPositions('creditnote', 'pos')"]],
		'customer' => ['title' => 'TABS_CUSTOMER'],
		'shipping' => ['title' => 'TABS_SHIPPING_ADDRESS'],
		'files' => ['title' => 'TABS_FILES', 'html' => $this->Files()],
		'finish' => ['title' => 'TABS_FINISH', 'html' => $this->Finish(), 'a_attrs' => ['onclick'=>"previewPdf()"]],
	],
]); ?>
<?php echo $this->Popup(); ?>
