<?php		 
$this->title = $this->translate('CREDIT_NOTES');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="creditnoteid" width="5%">
				<?php echo $this->translate('CREDIT_NOTES_CREDIT_NOTE_ID'); ?>
			</th>
			<th class="title" width="28%">
				<?php echo $this->translate('CREDIT_NOTES_TITLE'); ?>
			</th>
			<th class="contactid" width="5%">
				<?php echo $this->translate('CREDIT_NOTES_CONTACT'); ?>
			</th>
			<th class="billingaddress" width="20%">
				<?php echo $this->translate('CREDIT_NOTES_BILLING_ADDRESS'); ?>
			</th>
			<th class="notes" width="15%">
				<?php echo $this->translate('CREDIT_NOTES_NOTES') ?>
			</th>
			<th class="creditnotedate" width="8%">
				<?php echo $this->translate('CREDIT_NOTES_CREDIT_NOTE_DATE'); ?>
			</th>
			<th class="total" width="8%">
				<?php echo $this->translate('CREDIT_NOTES_TOTAL'); ?>
			</th>
			<th class="state" width="6%">
				<?php echo $this->translate('CREDIT_NOTES_STATE'); ?>
			</th>
			<th class="pin" width="8%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->creditnotes as $creditnote) : ?>
		<tr class="state<?php echo $creditnote->state; ?><?php echo $creditnote->pinned ? ' pinned' : ''; ?>">
			<td><input class="id" type="checkbox" value="<?php echo $creditnote->id ?>" name="id"/></td>
			<td class="creditnoteid">
				<?php if($creditnote->creditnoteid) : ?>
					<a href="<?php echo $this->url(array('controller'=>'creditnote', 'action'=>'edit', 'id'=>$creditnote->id)); ?>">
						<?php echo $this->escape($creditnote->creditnoteid); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_TITLE') ?>" class="title">
				<a href="<?php echo $this->url(array('controller'=>'creditnote', 'action'=>'edit', 'id'=>$creditnote->id)); ?>">
					<?php echo $creditnote->title ? $this->escape($creditnote->title) : $this->escape($creditnote->id); ?>
				</a>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_CONTACT') ?>" class="contactid">
				<?php if($creditnote->contactid) : ?>
					<a href="<?php echo $this->url(array('module'=>'contacts', 'controller'=>'contact', 'action'=>'edit', 'id'=>$creditnote->cid)); ?>">
						<?php echo $this->escape($creditnote->contactid); ?><br/>
						<?php echo $this->escape($creditnote->billingname1); ?>
						<?php if($creditnote->billingname2) echo "<br/>".$this->escape($creditnote->billingname2); ?>
					</a>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_BILLING_ADDRESS') ?>" class="billingaddress">
				<?php echo $this->escape($creditnote->billingstreet); ?><br/>
				<?php echo $this->escape($creditnote->billingpostcode); ?><br/>
				<?php echo $this->escape($creditnote->billingcity); ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_NOTES') ?>" class="notes">
				<?php if($creditnote->notes) : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $creditnote->notes; ?>" data-type="textarea"><?php echo $creditnote->notes; ?></pre>
				<?php else : ?>
					<pre class="editable" data-name="notes" data-value="<?php echo $creditnote->notes; ?>" data-type="textarea" data-empty="true"><?php echo $this->translate('TOOLBAR_NEW') ;?></pre>
				<?php endif; ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_CREDIT_NOTE_DATE') ?>" class="creditnotedate">
				<?php if($creditnote->creditnotedate) echo $this->escape(date("d.m.Y", strtotime($creditnote->creditnotedate))); ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_TOTAL') ?>" class="total">
				<?php echo $this->escape($creditnote->total); ?>
			</td>
			<td data-label="<?php echo $this->translate('CREDIT_NOTES_STATE') ?>" class="state">
				<?php if($creditnote->state == '105' || $creditnote->state == '106') : ?>
					<?php echo $this->translate($this->escape($this->options['states'][$creditnote->state])); ?>
				<?php else : ?>
					<span class="editable" data-name="state" data-value="<?php echo $creditnote->state; ?>" data-type="select"><?php echo $this->translate($this->escape($this->options['states'][$creditnote->state])); ?></span>
				<?php endif; ?>
			</td>
			<td class="pin">
				<?php if($creditnote->pinned) : ?>
					<input type = "button" onclick = "pin(<?php echo $creditnote->id ?>)" value = "<?php echo $this->translate('DETACH') ?>">
				<?php else : ?>
					<input type = "button" onclick = "pin(<?php echo $creditnote->id ?>)" value = "<?php echo $this->translate('ATTACH') ?>">
				<?php endif; ?>
			</td>
			<td class="buttons">
				<?php if($creditnote->state == '105' || $creditnote->state == '106') : ?>
					<?php echo $this->toolbar->viewInline; ?>
				<?php else : ?>
					<?php echo $this->toolbar->editInline; ?>
				<?php endif; ?>
				<?php echo $this->toolbar->copyInline; ?>
				<?php echo $this->toolbar->pdfInline; ?>
			</td>
		</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td></td>
			<td class="toolbar">
				<?php echo $this->ToolbarBottom(); ?>
			</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="total">
				<?php echo $this->creditnotes->total; ?>
			</td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
