<?php
$this->title = $this->translate('SHOPS_ACCOUNTS');
$this->headTitle($this->title);
//echo $this->Messages();
//echo $this->ActiveFilter();
?>

<?php if(isset($this->slides)) : ?>
	<!-- Carousel Section -->
	<section id="carousel" class="carousel slide" data-ride="carousel" data-interval="5000"><!-- Set interval to 5000 milliseconds (5 seconds) -->
		<ol class="carousel-indicators">
			<?php foreach($this->slides as $index => $slide) : ?>
				<li data-target="#carousel" data-slide-to="<?php echo $index; ?>" <?php echo $index === 0 ? 'class="active"' : ''; ?>></li>
			<?php endforeach; ?>
		</ol>
		<div class="carousel-inner">
			<?php foreach($this->slides as $index => $slide) : ?>
				<div class="carousel-item<?php echo $index === 0 ? ' active' : ''; ?>">
					<a href="<?php echo $slide->url; ?>">
						<img src="<?php echo $this->baseUrl(); ?>/media/slide/1/0/100/<?php echo $slide->image; ?>" class="d-block w-100" alt="...">
					</a>
					<div class="carousel-caption d-md-block text-left align-middle">
						<a href="<?php echo $slide->url; ?>">
							<h2><?php echo $slide->title; ?></h2>
						</a>
						<a href="<?php echo $slide->url; ?>">
							<p><?php echo $slide->description; ?></p>
						</a>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</section>
<?php endif; ?>
<?php $content = $this->page['content']; ?>
<?php echo $content; ?>
