<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<ul class="tabs">
	<li<?php if($this->activeTab == "#tabOverview") : ?> class="active"<?php endif; ?>>
		<a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
	<li<?php if($this->activeTab == "#tabImages") : ?> class="active"<?php endif; ?>>
		<a href="#tabImages"><?php echo $this->translate('TABS_IMAGES'); ?></a></li>
	<li<?php if($this->activeTab == "#tabDownloads") : ?> class="active"<?php endif; ?>>
		<a href="#tabDownloads"><?php echo $this->translate('TABS_DOWNLOADS'); ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content<?php if($this->activeTab == '#tabOverview' || !$this->activeTab) : ?> active<?php endif; ?>"">
		<form id="category" enctype="application/x-www-form-urlencoded" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-7">
					<dl class="form">
						<?php echo $this->form->id; ?>
						<?php echo $this->form->title; ?>
						<?php echo $this->form->subtitle; ?>
						<?php if($this->form->getValue('type') == 'shop') : ?>
							<?php echo $this->form->slug; ?>
							<?php echo $this->form->metatitle; ?>
							<?php echo $this->form->metadescription; ?>
						<?php endif; ?>
						<?php echo $this->form->description; ?>
						<?php echo $this->form->shortdescription; ?>
						<?php echo $this->form->minidescription; ?>
						<hr>
						<div id="tag" class="multiformContainer" data-parentid="<?php echo $this->form->getValue('id'); ?>" data-controller="tag">
							<?php echo $this->MultiForm('shops', 'tag', $this->tags, 'tag', 'TAGS'); ?>
						</div>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-5">
						<?php echo $this->form->header; ?>
						<?php echo $this->form->footer; ?>
				</div>
			</div>
		</form>
	</div>
	<div id="tabImages" class="tab_content<?php if($this->activeTab == '#tabImages') : ?> active<?php endif; ?>">
		<h3>Category Images</h3>
		<div class="image-gallery">
			<?php $type = 'image'; ?>
			<?php $folder = 'category'; ?>
			<?php if (count($this->media) > 0): ?>
				<form id="image" enctype="application/x-www-form-urlencoded" action="" method="post">
					<div class="image-grid">
						<?php foreach ($this->media as $file): ?>
							<?php if ($file->type == 'image') : ?>
								<div class="image">
									<a href="<?php echo $this->baseUrl(); ?>/media/<?php echo $this->escape($this->mediaPath); ?>/<?php echo $folder; ?>/<?php echo $this->escape($file->url); ?>" target="_blank">
										<img src="<?php echo $this->baseUrl(); ?>/media/<?php echo $this->escape($this->mediaPath); ?>/<?php echo $folder; ?>/<?php echo $this->escape($file->url); ?>" alt="<?php echo $this->escape($file->title); ?>" class="image-thumbnail" />
									</a>
									<div class="image-caption">
										<?php echo $this->imageForms[$file->id]->title; ?>
										(<?php echo $this->escape($file->url); ?>)
									</div>
									<div class="image-actions">
										<a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'media', 'action'=>'delete', 'folder'=>$folder, 'parentid'=>$this->id, 'id'=>$file->id, 'url' => $this->module.'|'.$this->controller.'|'.$this->action)); ?>" onclick="return confirm('Are you sure you want to delete this image?');" class="delete-link">Delete</a>
									</div>
								</div>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				</form>
			<?php else: ?>
				<p>No images available for this category.</p>
			<?php endif; ?>
		</div>
		<form action="<?php echo $this->url(array('module'=>'default', 'controller'=>'media', 'action'=>'upload')); ?>" method="post" enctype="multipart/form-data">
			<label for="imageUpload">Upload New Image:</label>
			<input type="file" name="media[]" multiple />

			<label for="subfolder">Select Subfolder:</label>
			<select name="subfolder" id="subfolder" required>
				<option value="0">Main Folder</option>
				<?php foreach ($this->subfolders[$folder] as $subfolder): ?>
					<option value="<?php echo $this->escape($subfolder); ?>"><?php echo $this->escape($subfolder); ?></option>
				<?php endforeach; ?>
			</select>

			<input type="hidden" name="admin" value="1" />
			<input type="hidden" name="type" value="<?php echo $type; ?>" />
			<input type="hidden" name="controller" value="category" />
			<?php if($this->form->getValue('type') == 'shop') : ?>
				<input type="hidden" name="module" value="shops" />
			<?php elseif($this->form->getValue('type') == 'item') : ?>
				<input type="hidden" name="module" value="items" />
			<?php elseif($this->form->getValue('type') == 'contact') : ?>
				<input type="hidden" name="module" value="contacts" />
			<?php endif; ?>
			<input type="hidden" name="folder" value="<?php echo $folder; ?>" />
			<input type="hidden" name="category_id" value="<?php echo $this->escape($this->id); ?>" />
			<button type="submit">Upload</button>
		</form>
	</div>
	<div id="tabDownloads" class="tab_content<?php if($this->activeTab == '#tabDownloads') : ?> active<?php endif; ?>">
		<h3>Category Downloads</h3>
		<div class="download-list">
			<?php $type = 'download'; ?>
			<?php $folder = 'downloads'; ?>
			<?php if (count($this->media) > 0): ?>
				<form id="download" enctype="application/x-www-form-urlencoded" action="" method="post">
					<ul>
						<?php foreach ($this->media as $file): ?>
							<?php if ($file->type == 'download') : ?>
								<li class="download">
									<a href="<?php echo $this->baseUrl(); ?>/media/<?php echo $this->escape($this->mediaPath); ?>/<?php echo $folder; ?>/<?php echo $this->escape($file->url); ?>" target="_blank">
										<?php echo $this->escape($file->title); ?>
									</a> | <?php echo $this->escape($file->url); ?>
									<!--<div class="image-caption">
										<?php echo $this->imageForms[$file->id]->title; ?>
										(<?php echo $this->escape($file->url); ?>)
									</div>-->
									<div class="download-actions">
										<a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'media', 'action'=>'delete', 'folder'=>$folder, 'parentid'=>$this->id, 'id'=>$file->id, 'url' => $this->module.'|'.$this->controller.'|'.$this->action)); ?>" onclick="return confirm('Are you sure you want to delete this image?');" class="delete-link">Delete</a>
									</div>
								</li>
							<?php endif; ?>
						<?php endforeach; ?>
					</ul>
				</form>
			<?php else: ?>
				<p>No images available for this category.</p>
			<?php endif; ?>
		</div>
		<form action="<?php echo $this->url(array('module'=>'default', 'controller'=>'media', 'action'=>'upload')); ?>" method="post" enctype="multipart/form-data">
			<label for="imageUpload">Upload New Image:</label>
			<input type="file" name="media[]" multiple />

			<label for="subfolder">Select Subfolder:</label>
			<select name="subfolder" id="subfolder" required>
				<option value="0">Main Folder</option>
				<?php foreach ($this->subfolders[$folder] as $subfolder): ?>
					<option value="<?php echo $this->escape($subfolder); ?>"><?php echo $this->escape($subfolder); ?></option>
				<?php endforeach; ?>
			</select>

			<input type="hidden" name="admin" value="1" />
			<input type="hidden" name="type" value="<?php echo $type; ?>" />
			<input type="hidden" name="controller" value="category" />
			<?php if($this->form->getValue('type') == 'shop') : ?>
				<input type="hidden" name="module" value="shops" />
			<?php elseif($this->form->getValue('type') == 'item') : ?>
				<input type="hidden" name="module" value="items" />
			<?php elseif($this->form->getValue('type') == 'contact') : ?>
				<input type="hidden" name="module" value="contacts" />
			<?php endif; ?>
			<input type="hidden" name="folder" value="<?php echo $folder; ?>" />
			<input type="hidden" name="category_id" value="<?php echo $this->escape($this->id); ?>" />
			<button type="submit">Upload</button>
		</form>
	</div>
	<?php if($this->dirwritable) : ?>
		<div id="tabFiles" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
			<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?lang=de&type=0" width="100%" height="700px"></iframe>
		</div>
	<?php endif; ?>
</div>

<!--<div id="tabImages" class="tab_content<?php if($this->activeTab == '#tabFiles') : ?> active<?php endif; ?>">
	<form id="item" enctype="application/x-www-form-urlencoded" action="" method="post">
		<div class="row">
			<div class="col-sm-12 col-lg-7">
				<iframe src="<?php echo $this->baseUrl(); ?>/library/FileManager/dialog.php?controller=item&lang=de&type=0" width="100%" height="500px"></iframe>
				<dl class="form">
					<?php echo $this->form->getElement('image') ?>
				</dl>
			</div>
			<div class="col-sm-12 col-lg-5">
				<?php if($this->form->getElement('image') && file_exists(BASE_PATH."/files/images/".$this->form->getElement('image'))); { ?>
					<p><img id="preview" src="<?php echo $this->baseUrl().'/files/images/'.$this->form->getValue('image'); ?>"></p>
				<?php } ?>
			</div>
		</div>
	</form>
</div>-->
