<?php 
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->TinyMCE();
echo $this->FileManager();
?>

<?php echo $this->form->renderForm([
	'id' => 'category',
	'activeTab' => $this->activeTab,
	'tabs' => [
		'overview' => ['title' => 'TABS_OVERVIEW'],
		'images' => ['title' => 'TABS_IMAGES', 'html' => $this->Media(['module' => 'shops', 'controller' => 'category', 'parentid' => $this->id, 'type' => 'image', 'path' => 'category'])],
		'downloads' => ['title' => 'TABS_DOWNLOADS', 'html' => $this->Media(['module' => 'shops', 'controller' => 'category', 'parentid' => $this->id, 'type' => 'download', 'path' => 'download'])]
	]
]); ?>
