<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id" width="5%">
				<?php echo $this->translate('ADMIN_CLIENT_ID'); ?>
			</th>
			<th class="name" width="20%">
				<?php echo $this->translate('ADMIN_COMPANY'); ?>
			</th>
			<th class="phone" width="12%">
				<?php echo $this->translate('ADMIN_ADDRESS'); ?>
			</th>
			<th class="street" width="12%">
				<?php echo $this->translate('ADMIN_POSTCODE'); ?>
			</th>
			<th class="postcode" width="7%">
				<?php echo $this->translate('ADMIN_CITY'); ?>
			</th>
			<th class="postcode" width="7%">
				<?php echo $this->translate('ADMIN_COUNTRY'); ?>
			</th>
			<th class="city" width="10%">
				<?php echo $this->translate('ADMIN_EMAIL'); ?>
			</th>
			<th class="country" width="10%">
				<?php echo $this->translate('ADMIN_WEBSITE'); ?>
			</th>
			<th class="category" width="12%">
				<?php echo $this->translate('ADMIN_LANGUAGE'); ?>
			</th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->clients as $client) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $client->id ?>" name="id"/></td>
				<td class="id">
					<?php echo $this->escape($client->id); ?>
				</td>
				<td class="name">
					<span class="editable" data-name="company"><?php echo $this->escape($client->company); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="address"><?php echo $this->escape($client->address); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="postcode"><?php echo $this->escape($client->postcode); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="city"><?php echo $this->escape($client->city); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="country"><?php echo $this->escape($client->country); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="email"><?php echo $this->escape($client->email); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="website"><?php echo $this->escape($client->website); ?></span>
				</td>
				<td class="name">
					<span class="editable" data-name="language"><?php echo $this->escape($client->language); ?></span>
				</td>
				<td class="buttons">
					<?php echo $this->Button('copy'); ?>
					<?php echo $this->Button('delete'); ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="add">
			<td>
			</td>
			<td>
				<?php echo $this->translate('TOOLBAR_NEW'); ?>
			</td>
			<td>
				<?php echo $this->form->company; ?>
			</td>
			<td>
				<?php echo $this->form->address; ?>
			</td>
			<td>
				<?php echo $this->form->postcode; ?>
			</td>
			<td>
				<?php echo $this->form->city; ?>
			</td>
			<td>
				<?php echo $this->form->country; ?>
			</td>
			<td>
				<?php echo $this->form->email; ?>
			</td>
			<td>
				<?php echo $this->form->website; ?>
			</td>
			<td>
				<?php echo $this->form->language; ?>
			</td>
			<td class="buttons">
				<?php echo $this->toolbar->save; ?>
				<?php //echo $this->toolbar->cancel; ?>
			</td>
		</tr>
	</tbody>
</table>
