<?php
$this->title = $this->translate('CONTACTS_NEW_DOWNLOAD');
$this->headTitle($this->title);
?>

<ul class="tabs">
	<li><a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW') ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content">
		<form id="download" name="download" enctype="multipart/form-data" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-7">
					<dl class="form">
						<?php echo $this->form->getElement('title') ?>
						<?php echo $this->form->getElement('setid'); ?>
						<?php echo $this->form->getElement('file') ?>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-5">
				</div>
			</div>
		</form>
	</div>
</div>
