<?php
$this->title = $this->form->getValue('title');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->FileManager();
?>

<ul class="tabs">
	<li<?php if($this->activeTab == "#tabOverview") : ?> class="active"<?php endif; ?>>
		<a href="#tabOverview"><?php echo $this->translate('TABS_OVERVIEW'); ?></a></li>
</ul>

<div class="tab_container">
	<div id="tabOverview" class="tab_content<?php if($this->activeTab == '#tabOverview' || !$this->activeTab) : ?> active<?php endif; ?>">
		<form id="download" enctype="multipart/form-data" action="" method="post">
			<div class="row">
				<div class="col-sm-12 col-lg-6">
					<dl class="form">
						<?php echo $this->form->getElement('id'); ?>
						<?php echo $this->form->getElement('title'); ?>
						<?php echo $this->form->getElement('setid'); ?>
						<?php echo $this->form->getElement('file') ?>
						<?php echo $this->form->getElement('submit') ?>
					</dl>
				</div>
				<div class="col-sm-12 col-lg-6">
					<iframe src="<?php echo $this->baseUrl(); ?>/files/downloads/<?php echo $this->downloadsurl.$this->form->getValue('filename'); ?>" width="100%" height="700px"></iframe>
				</div>
			</div>
		</form>
	</div>
</div>
