<?php
$this->title = $this->translate('ITEMS_NEW_LEDGER');
$this->headTitle($this->title);
echo $this->Messages();
?>

<form
	id="ledger"
	name="ledger"
	enctype="application/x-www-form-urlencoded"
	action=""
	method="post"
>
	<div class="row">
		<div class="col-sm-12 col-lg-7">
			<div class="dw-form-row">
				<?php echo $this->form->renderElementWithAttribs('warehouseid') ?>
				<?php echo $this->form->renderElementWithAttribs('type') ?>
				<?php echo $this->form->renderElementWithAttribs('reason') ?>
				<?php echo $this->form->renderElementWithAttribs('ledgerdate') ?>
				<?php echo $this->form->renderElementWithAttribs('comment') ?>
			</div>
		</div>
	</div>

	<div id="ledgerPositions">
	</div>

	<button
		type="button"
		id="addLedgerPosition"
	>
		<?php echo $this->translate('ITEMS_LEDGER_ADD_POSITION') ?>
	</button>

	<button type="submit">
		<?php echo $this->translate('ITEMS_LEDGER_BOOK') ?>
	</button>
</form>
