<?php
$this->title = $this->translate('ITEMS_LEDGER');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->ActiveFilter();
?>

<table id="data">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="sku" width="10%">
				<?php echo $this->translate('ITEMS_SKU'); ?>
			</th>
			<th class="title" width="32%">
				<?php echo $this->translate('ITEMS_TITLE'); ?>
			</th>
			<th class="cost" width="8%">
				<?php echo $this->translate('ITEMS_LEDGER_COMMENT'); ?>
			</th>
			<th class="cost" width="8%">
				<?php echo $this->translate('ITEMS_LEDGER_TYPE'); ?>
			</th>
			<th class="price" width="8%">
				<?php echo $this->translate('ITEMS_LEDGER_DOCUMENT'); ?>
			</th>
			<th class="quantity" width="8%">
				<?php echo $this->translate('ITEMS_LEDGER_PRICE'); ?>
			</th>
			<th width="8%"><?php echo $this->translate('ITEMS_LEDGER_QUANTITY'); ?></th>
			<th width="8%"><?php echo $this->translate('ITEMS_CATEGORY'); ?></th>
			<th width="8%"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->ledger as $ledger) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $ledger->id ?>" name="id"/></td>
				<td data-label="<?php echo $this->translate('ITEMS_SKU') ?>" class="sku">
					<?php echo $this->escape($ledger->sku); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_TITLE') ?>" class="title">
					<?php echo $this->escape($ledger->title); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_LEDGER_COMMENT') ?>" class="comment">
					<?php //echo $this->escape($ledger->comment); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_LEDGER_TYPE') ?>" class="doctype">
					<?php //if($ledger->type == 'inflow') echo $this->translate('ITEMS_LEDGER_INFLOW'); ?>
					<?php //if($ledger->type == 'outflow') echo $this->translate('ITEMS_LEDGER_OUTFLOW'); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_LEDGER_DOCUMENT') ?>" class="cost">
					<?php //if($ledger->doctype == 'invoice') : ?>
						<a href="<?php //echo $this->url(array('module'=>'sales', 'controller'=>'invoice', 'action'=>'view', 'id'=>$ledger->docid));?>">
							<?php //echo $this->translate('INVOICE'); ?> <?php //echo $this->escape($ledger->invoiceid);?>
						</a>
					<?php //endif; ?>
					<?php if($ledger->doctype == 'creditnote') : ?>
						<a href="<?php echo $this->url(array('module'=>'sales', 'controller'=>'creditnote', 'action'=>'view', 'id'=>$ledger->docid));?>">
							<?php echo $this->translate('CREDIT_NOTE'); ?> <?php echo $this->escape($ledger->creditnoteid);?>
						</a>
					<?php endif; ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_LEDGER_PRICE') ?>" class="price">
					<?php echo $this->escape($ledger->price); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_LEDGER_QUANTITY') ?>" class="quantity">
					<?php echo $this->escape($ledger->quantity); ?>
				</td>
				<td data-label="<?php echo $this->translate('ITEMS_CATEGORY') ?>" class="category">
					<?php if($ledger->catid && isset($this->options['categories'][$ledger->catid])) echo $this->escape($this->options['categories'][$ledger->catid]['title']); ?>
				</td>
				<td class="buttons">
					<?php echo $this->toolbar->editInline; ?>
					<?php echo $this->toolbar->copyInline; ?>
					<?php echo $this->toolbar->deleteInline; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr class="bottom">
			<td></td>
			<td>
				<div class="toolbar bottom">
					<?php echo $this->ToolbarBottom(); ?>
				</div>
			</td>
			<td></td>
		</tr>
	</tbody>
</table>
