<?php
$this->title = $this->translate('ADMIN');
$this->headTitle($this->title);
echo $this->Messages();
echo $this->AdminMenu();
?>

<table id="data" class="permissions">
	<thead>
		<tr>
			<th width="2%"><input type="checkbox" class="checkall" name="checkall"/></th>
			<th class="id">
				<?php echo $this->translate('ADMIN_ID'); ?>
			</th>
			<?php foreach($this->modules as $module) : ?>
			<th class="<?php echo $this->escape($module); ?>">
                <?php echo $this->escape($module); ?>
			</th>
			<?php endforeach; ?>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->permissions as $permission) : ?>
			<tr>
				<td><input class="id" type="checkbox" value="<?php echo $permission->id ?>" name="id"/></td>
				<td class="id">
					<?php echo $this->escape($permission->id); ?>
				</td>
				<?php foreach($this->modules as $module) : ?>
				<td class="<?php echo $this->escape($module); ?>">
                    <input type="hidden" name="module" class="module" value="<?php echo $this->escape($module); ?>">
					<?php foreach($permission->$module as $controller => $actions) : ?>
                        <input type="hidden" name="controller" class="controller" value="<?php echo $this->escape($controller); ?>">
                        <h4><?php echo $this->escape($controller); ?></h4>
				        <?php echo $this->forms[$permission->id][$module][$controller]->add; ?>
				        <?php echo $this->forms[$permission->id][$module][$controller]->edit; ?>
				        <?php echo $this->forms[$permission->id][$module][$controller]->view; ?>
				        <?php echo $this->forms[$permission->id][$module][$controller]->delete; ?>
					<?php endforeach; ?>
				</td>
				<?php endforeach; ?>
				<td></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
